### ISSUE TITLE
Remove "classic" examples option

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1037]
From what I understand, adding a config option for `"examples": "classic"` is a sort of future-proofing move when inserting example components.

I can't find any reason why this would be necessary. It may have seemed like a good idea at the time, but it's adding some unnecessary branching in our code when we don't know what the future will look like.

I propose we pull this out of our generated config and things like `addPluginComponentExample`, and only add a check sometime down the road if we need to.

**Comment by skellock** [comment]
Yes to deleting code. Always.

**Comment by jamonholmgren** [comment]
You woke out of a deep sleep just to tell me that, didn't you @skellock .

**Comment by GantMan** [comment]
@jamonholmgren and @skellock 

We need an indicator to tell us if the person wants an example or not.   Rather than saying `examples: true` I went with `classic` which not only says true, but gives us how we did it.

Should we move to storybook, or some other style of examples, `examples: true` won't cut it.

**Comment by jamonholmgren** [comment]
Gotcha, thanks @GantMan .
