### ISSUE TITLE
how to specify boilerplate when using ignite attach so I can use its generators

### ISSUE THREAD

**Issue by vesper8** [infinitered/ignite#1062]
I have a project that is built with NativeBase and I want to ignite attach while specifying the boilerplate so : ignite attach --boilerplate native-base-boilerplate

How can I achieve this? 

I want to be able to use the generators from the native-base-boilerplate.

Using their generators is all I care about.

If I can't do this in one command.. then how? 

Create a new project with the BP and then copy over which files and which folders?

**Comment by vesper8** [comment]
I was able to do this via
```
ignite attach
ignite add boilerplate
```

even though ignite add is supposed to be for plugins, and boilerplates are not listed when you do `ignite list`. It still works.. kinda.. but not really

it adds the boilerplate as a npm package. But doesn't copy any of the files necessary for the boilerplate code to work.

I opened another issue for this 1063

This one can be closed... though I think it should be possible to pass a -b option to ignite attach.. and of course the behaviour needs to be rectified so the generators are actually functional after

**Comment by skellock** [comment]
> It still works.. kinda.. but not really

A boilerplate is only run when you start your project from one.

The ignite generators are tightly coupled to the boilerplate.  That's why they live there.  You can still add the boilerplate later `ignite add ir-boilerplate` if you still want the generators.

But at that point, it's on you to setup the directory structure.  You can do this (albeit manually) by `ignite new FreshProject` and then copying the required files & directories over.

>  should be possible to pass a -b option to ignite attach

Interesting. Hit us up with a PR!

> This one can be closed

Roger that.  Thanks for taking the to file these issues.
