### ISSUE TITLE
Boilerplate replacing redux with apollo store

### ISSUE THREAD

**Issue by KenilDomadia** [infinitered/ignite#1181]
### I think it would be really cool to have ignite boilerplate to include apollo integration

I love the work ignite has done with react native project. As there is a huge community out there using graphql clients with react native project. I searched internet and could not find ideal boilerplate for react-native with apollo which manages its own store replacing redux.

Are you guys planning on for any such thing? 

This is first time I am writing an issue, please pardon the language.

**Comment by leakim34** [comment]
Agree !

**Comment by nenjamin2405** [comment]
totally agree !!

**Comment by skellock** [comment]
Pretty much everyone here is sold on GraphQL. We’ve only had 1 client ask/want it and that was a web app.

I’d love to see this too, but it won’t be coming out of our camp just yet since we derive our boilerplates from our client work. I’m willing to bet by the end of this year the story will be completely different though!

So, instead of source code, please accept this emoji horse🐴 in the meantime.

**Comment by samtoya** [comment]
+1 for Apollo integration.

**Comment by jamonholmgren** [comment]
> it won’t be coming out of our camp just yet since we derive our boilerplates from our client work

So Steve is still correct, here -- we still derive boilerplates from client work. While we have some Apollo work, it's still not a high percentage of our work, so we're holding off on it. We still like Apollo though!

**Comment by vamshi9666** [comment]
+1 graphl
