### ISSUE TITLE
TypeError: undefined is not an object(evaluating 'route.routeName')

### ISSUE THREAD

**Issue by SachArora** [infinitered/ignite#1210]
react-native-cli: 2.0.1
react-native: 0.50.4

after generate ignite app via 'ignite new IgniteJHipsterSampleApp --boilerplate ignite-jhipster'
![screenshot from 2017-12-20 12-59-27](https://user-images.githubusercontent.com/22761374/34195914-cd923980-e585-11e7-8368-7641d52b3846.png)

my virtual device show's this error on 'react-native run-android'

![screenshot from 2017-12-20 12-51-39](https://user-images.githubusercontent.com/22761374/34195734-11d35e2c-e585-11e7-9fd2-c2288d7daea7.png)

I'm already set my adb path in local.properties file which is in Android folder of Ignite apps directory.
I'm new to ignite, tell me how to resolve this. Thank you

**Comment by ruddell** [comment]
Transitive dependencies are the worst...  react-navigation had [undocumented breaking changes](https://github.com/react-community/react-navigation/issues/3148) to DrawerNavigators. I added a [workaround](https://github.com/ruddell/ignite-jhipster/commit/0f68ca781ca2a42e2a152c26f3c54489048e7d4a) in the boilerplate so if you try again, it should work.

This is an ignite-jhipster bug instead of this project (ignite), so please open bugs in [that repository](https://github.com/ruddell/ignite-jhipster) in the future.  Thank you for reporting this bug 😄

**Comment by skellock** [comment]
Closing. Let me know if there’s something actionable on my end.

I agree. Dependencies fighting dependencies in your dependencies makes me want to get a job at Dairy Queen. At least they Treat You Right ™️.
