### ISSUE TITLE
Please release new version with latest packages

### ISSUE THREAD

**Issue by AlirezaAkbarix** [infinitered/ignite#1250]
![capture](https://user-images.githubusercontent.com/15062651/38392118-94275586-393b-11e8-8973-1e045cac6768.PNG)

I think it's time to release Bowser! current packages are too old and boilerplate itself is outdated (redux, dev screens, ...)

Is it clear when will new version released?

**Comment by kevinvangelder** [comment]
Hey there, thanks for your enthusiasm! We're currently using Bowser in a project to evaluate it, and I can confidently say that it's currently not up to the Infinite Red standard. We'll be sure to let people know when it's ready for public use.

**Comment by skellock** [comment]
We’re in the process of wrapping up. Internally we’ve built several apps with this stack (5 and counting) so we’re still refining.

Packaging it up for public consumption is a little different because some things need to change.  For example we have internal tools that help us build things out, but some techniques don’t make much sense without them.

The stack looks like: react-navigation, mobx, mobx-state-tree, storybook, and a more collocated directory structure where views are grouped by domain.

**Comment by AlirezaAkbarix** [comment]
@kevinvangelder, @skellock, Thank you guys for your complete answers.

**Comment by kevinvangelder** [comment]
You can see the alpha version of our new boilerplate here: https://github.com/infinitered/ignite-ir-boilerplate-bowser
