### ISSUE TITLE
Give ignite the ability to generate a web project.

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#1279]
Hello, 

A fair while back I started a new boilerplate (based on andross) for ignite in order to bootstrap a react-based single-page-app. I've used this in a project for a fair while now and I'm confident enough I am at a place where I can inflict it upon the rest of the world. :world_map: I've reviewed this [history](https://github.com/infinitered/ignite/pull/1132) so far.

Enter teensy problem. :question: 
There is a hard coded dependency on `react-native` which means that ignite won't run unless the `react-native-cli` is installed.  Here are some wise words from Rich Evans, copypastaed from the gluegun slack channel: 

> If you are writing a boilerplate it seems like hooking it up with ignite makes the most sense. Maybe a good first step would be making a PR to ignite to remove the hard dependency on `react-native` 

So I am going down this path, but of course I have some questions/thoughts/things I want to confirm:

1. [Here](https://github.com/infinitered/ignite/blob/master/src/cli/check.js#L29) there is a check to make sure RN is installed. I intend to modify this so that there is a message displayed, instead of stopping the whole process completely.

2. If I allow this check to pass, but don't install `react-native-cli` the next thing that happens is when I go to run `ignite new` projectname, the process stops with:

```
🔥 igniting app gantman
? Which boilerplate would you like to use? Bowser (alpha) (React Navigation, MobX State Tree, & TypeScript)
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✖ failed to add React Native 0.55.4
```
I could add some text to this message so that the developer knows that they need to check `react-native-cli`.

3. I'm installing create-react-app inside the `boilerplate.js` file, sort of like this:
```  
  spinner.text = '▸ installing Create React App'
  spinner.start()
  spinner.text = 'installed Create React App'
  await system.run('npm install create-react-app')
  spinner.stop().succeed()
```
Is this kind of what you had in mind?

4. Debug mode requires react-native-cli to be installed. I'm thinking I'll leave this as a #TODO for some other keen bean.

PPS. Sorry about the War and Peace-esque issue length! :books:

**Comment by juddey** [comment]
Kevin, not sure if your comment means I should change what I have stated I will do or if its more of an observation. I'll assume the latter unless you say otherwise.

**Comment by skellock** [comment]
I love reading your issue @juddey.  You always explain your situation so carefully and thoroughly. 

Personally, my take on this is that much of ignite is tailored specifically to React Native  and not a generic boilerplating framework. 

Much of ignite’s core functionality comes from gluegun. If I were starting a boilerplate that was not react native, I’d consider dropping down to that (or something like that). 

Gluegun has matured quite nicely due to @jamonholmgren’s fantastic work transforming it into 2.0. Ignite uses 1.0 and the current plan is to keep it there.

This is my take.

If you think that’s not right for you, I’m sure we’d accept PRs to this repo that didn’t break compatibility with existing boilerplates.

**Comment by juddey** [comment]
Hey @skellock thanks for your thoughts. I had been a little more verbose than usual because this was something that wasn't just a "hey, heres a pr to add an emoji" :palm_tree:  

When I started my boilerplate gluegun was in its infancy and so attaching to ignite seemed to be the most appropriate way forward. Time has passed and things change. I also realise that IR might not make use of a react `spa` type boilerplate too so supporting something like this in what might be considered your core app probably doesn't make a lot of sense.

However, the whole purpose of starting this thread was to start to get the boilerplate-for-web out there, and I want to push on with that - `is there an ignite boilerplate for web?` is still a question that comes through the slack community. 

This being the case, and given I am almost finished the boilerplate, I'm going to keep the dependency on `ignite`, and also `react-native`  for now, the logic being that most people will have these two on their system already, and installing that extra dependency is not going to be too onerous a task. I will revisit this in the future as taking on a build of a cli is not something I'd planned for, and I'm trying to be a touch pragmatic as I am not sure of the uptake of a boilerplate-for-web, and what future requirements might be. :crystal_ball: 

Given this, I'd hope that you'd accept a PR at some point to add this new boilerplate to the ignite family, which'll be in the form of some links in the documentation to this new option.

I'll close this off for now but feel free to comment if there is anything further. :peace_symbol:

**Comment by jamonholmgren** [comment]
Thanks @juddey, this is a really well done post.

> Personally, my take on this is that much of ignite is tailored specifically to React Native and not a generic boilerplating framework.

Steve is correct. However, we would like Ignite to be less React Native-focused. There are several useful things built-in to Ignite that Gluegun doesn't provide, and having it be more of a generic boilerplate platform is a goal for us.

We haven't done that ourselves because we typically use [Mithril](https://github.com/infinitered/mithril) (Elixir/Phoenix) for web projects and don't do a lot of React-only web projects. But I'm certainly not opposed to the direction you're going.

> Given this, I'd hope that you'd accept a PR at some point to add this new boilerplate to the ignite family, which'll be in the form of some links in the documentation to this new option.

Absolutely. In fact, I'd like to add an option when you're spinning up a new project:

```
• Infinite Red Bowser (beta) - React Native boilerplate using MobX
• Infinite Red Andross - React Native boilerplate using Redux
• List third party boilerplates
```

In that third option, we'd include your boilerplate as an option.

**Comment by juddey** [comment]
@jamonholmgren Circling back on this now (as I am listening to [Building Infinite Red 5](https://building.infinite.red/5)) to say: 

* thanks for the clarification & taking the time to respond to a closed issue :+1: 
* I've got the web-boilerplate mostly running and am using it to spin up a new 'thing' :hammer: 
* I'm going to leave the `react-native` dependency for now, but will open an issue in the future to discuss how we can remove it. :heavy_minus_sign: 
* I'll keep on **_wedging_** (quote @twerth), so expect to hear from me again soon! :tada:

**Comment by sesam** [comment]
Got here researching how to use `ignite` to create something that also supports `react-native-web`, which isn't exactly what @juddey wanted, but maybe still a possibility?

(I'm currently comparing https://github.com/drgx/react-native-plus-web and https://github.com/zzz945/react-native-web-boilerplate and SSR https://github.com/jaredpalmer/razzle/tree/master/examples/with-react-native-web since it seems it's easier to start from a working whole (mess of) components and then take things out, than to start with less and integrate while figuring out which are compatible with what.)

**Comment by juddey** [comment]
Hey, @sesam. We're having a similar kind of discussion in #1301 (and you can see a quick progress update there too). We're probably going to need to have some bikeshedding discussions (like typescript/not etc etc) on this kind of thing, if you're interested then subscribe to that issue :)

**Comment by daoudjahdou** [comment]
Hey any updates about this ? having ignite working with react native web would be awesome !

**Comment by jamonholmgren** [comment]
@daoudjahdou No updates, unfortunately! We still haven't had a client project where that's been a first-class concern.

**Comment by affanhashone** [comment]
@jamonholmgren  Did You Find any ignite base web project ?

**Comment by jamonholmgren** [comment]
@affanhashone Not at this time.

**Comment by LzazSports** [comment]
@jamonholmgren  i created my own using ignite. Thanks

**Comment by jamonholmgren** [comment]
Hey folks, we have a new experimental web boilerplate using Next.js. Do `ignite new MyApp -b next-js` to try it out.

We don't have MobX-State-Tree or even TypeScript on it yet, but plan to evolve it over time. Next.js is an awesome web framework.

**Comment by thphuc** [comment]
Hi @jamonholmgren 

Is there any update on ignite for web?
