### ISSUE TITLE
Cannot create a new Ignite project - yarn is being forced during install

### ISSUE THREAD

**Issue by manbearshark** [infinitered/ignite#1280]
When I run `ignite new IgniteTestApp` I walk through all of the interactive options, then get the following errors:

🔥 igniting app IgniteTestApp
? Which boilerplate would you like to use? Andross (React Navigation, Redux, & Redux Saga
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.55.1 in 18.61s
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
? Would you like to include redux-persist? Yes
✖ ignite-ir-boilerplate-andross was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-andross --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-dev-screens was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-dev-screens --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-vector-icons was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-vector-icons --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-i18n was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-i18n --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-animatable was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-animatable --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-redux-persist was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-redux-persist --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✖ ignite-standard was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-standard --dev
error An unexpected error occurred: "Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/react-navigation/react-native-tab-view.git HEAD
Directory: /Users/igor/Development/IgniteTestApp/IgniteTestApp
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.".

----------
✔ configured git
✔ ignited IgniteTestApp in 52.86s

    Ignite CLI ignited IgniteTestApp in 52.86s

    To get started:

      cd IgniteTestApp
      react-native run-ios
      react-native run-android

To run in Android, make sure you've followed the latest react-native setup instructions at https://facebook.github.io/react-native/docs/getting-started.html before using ignite.
You won't be able to run react-native run-android successfully until you have.
      ignite --help

    Read the walkthrough at https://github.com/infinitered/ignite-ir-boilerplate-andross/blob/master/readme.md#boilerplate-walkthrough

    Need additional help? Join our Slack community at http://community.infinite.red.

    Now get cooking! 🍽
---

Not sure why yarn is being forced here, especially since it does not support Github interactive logins for https repository URLs, which I think is what is causing some of the failures above.

I can manually run these commands from the shell, and npm install works for the packages that are failing above.  For example, `npm install ignite-dev-screens --dev` works as expected.  Note that I have git configured to force ssh instead of https urls in my git configuration, this does not seem to work with yarn.

Steps to reproduce

npm install -g ignite-cli

ignite new IgniteTestApp

Same issue happens with the --npm option.  

I could not find any other references to this issue, not sure if I need to make some env changes, though I would prefer to be able to use yarn for other projects.

---
`ignite doctor` results:

{10:31}[2.5.0]~/Development ➭ ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores                   Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  directory          /Users/igor/Development

JavaScript
  node               9.9.0        /usr/local/bin/node
  npm                5.6.0        /usr/local/bin/npm
  yarn               1.5.1        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.0        /usr/local/bin/ignite

Android
  java               1.8.0_162    /usr/bin/java
  android home       -            undefined

iOS
  xcode              9.3.1

**Comment by oflarcade** [comment]
Same here:


`🔥 igniting app ITrivia
? Which boilerplate would you like to use? Andross (React Navigation, Redux, & Redux Saga
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.55.1 in 136.12s
? Would you like Ignite Development Screens? No
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
? Would you like to include redux-persist? Yes
✖ ignite-ir-boilerplate-andross was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-andross --dev
(node:3955) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning ../../package.json: No license field
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > @storybook/react-native@3.4.6" has unmet peer dependency "babel-runtime@>=6.0.0".
error /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer
Output:
ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: ENOENT: no such file or directory, chmod '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium']
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path:
   '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium' }

----------
✖ ignite-vector-icons was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-vector-icons --dev
(node:3968) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning ../../package.json: No license field
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > @storybook/react-native@3.4.6" has unmet peer dependency "babel-runtime@>=6.0.0".
error /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer
Output:
ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: ENOENT: no such file or directory, chmod '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium']
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path:
   '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium' }

----------
✖ ignite-i18n was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-i18n --dev
(node:4032) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning ../../package.json: No license field
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > @storybook/react-native@3.4.6" has unmet peer dependency "babel-runtime@>=6.0.0".
error /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer
Output:
ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: ENOENT: no such file or directory, chmod '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium']
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path:
   '/Users/oflcad/ITrivia/ITrivia/node_modules/puppeteer/.local-chromium/mac-564778/chrome-mac/Chromium.app/Contents/MacOS/Chromium' }

----------`

**Comment by meShakti** [comment]
facing the same issue , even if i use ignite with --npm option some of the modules is still running yarn

**Comment by delp--** [comment]
I found on my windows machine that I had to remove yarn before doing the command to create a new app.
so make sure you uninstall it before running -` ignite new IgniteTestApp`

Then once the new app is installed, you then need to install yarn before running the  - `npm install` command on that new app.

**Comment by kevinvangelder** [comment]
Related to #1142

**Comment by jamonholmgren** [comment]
I'm going to close in favor of #1142.
