### ISSUE TITLE
Why only React Native?

### ISSUE THREAD

**Issue by kirakik** [infinitered/ignite#1301]
First off, I'm a big fan of Ignite's, I think it's an amazing tool and I thank you guys for building it and working on it!

This issue is less of a bug report and more of a question, why only support React Native? It would be great to be able to bootstrap a monorepo React + React Native project using an Ignite boilerplate, or use an Ignite plugin to create a similar web and mobile component in one command (I use a yeoman generator for that now, but ignite would definitely makes the process easier). 

Are there any limitations? Is this something you guys would be willing to consider if there was enough interest from the community?

**Comment by GantMan** [comment]
Hey hey Kenza!  Great question!

**The structure of Ignite is two main parts.**
Gluegun CLI + Ignite React Native Specific Magic

Gluegun is structured to be a great CLI creator for ANYTHING that needs plugins.  I used it to make my Solidarity CLI.  Our thinking was this, "If we decide to Ignite for another language, we'd use Gluegun to write another set of helpers, under a new name."  So if we decided to do Ignite for Elixir, we'd call it some new brand, and write it in Gluegun.

Now... that being said... The world between React and React Native is so small, it's kind of a gray area.  Should we make a new CLI called "Nachos" that is specific to React, to be a sister project to Ignite?  Despite the naming problem, we want to make sure not to lock up horns on releases.  Also... big questions still sit on us for _how_ something like that should look.  When we React, we do so with Elixir, so our structure is specific to that... though I'm sure that opinion space goes crazy for everyone!

We're not opposed to mixing if we felt very confident on our strategy being used time and time again.  There's just a bit of research that we'd have to do first, and in the end we might not even include it in Ignite if it would get in the way.  

@jamonholmgren - any feedback I'm missing?  Is it time for Ignite for React?   That might be a pretty cool project!  Even if it's not called Nachos ;)

**Comment by kevinvangelder** [comment]
I don't think there would be any limitations in Ignite that would prevent someone from creating a monorepo boilerplate, but since that's not something we regularly do it isn't really a project we would have time to undertake or maintain.

**Comment by jamonholmgren** [comment]
I definitely agree. What I'd love to do is have a boilerplate that creates a React.js + React Native project that shares components and business logic, similar to how Bob Scarano from Squarespace presented at Chain React. I'm not sure when that will happen -- it needs to be something our clients want before we devote significant engineering time at Infinite Red -- but I really want it.

Thanks for the issue, @kirakik , definitely agree with you!

**Comment by juddey** [comment]
Hey there, so I thought I would jump on this and offer 2 cents.

I've wired in `create-react-app` into an ignite plugin so that it boilerplates a SPA web project loosely based on andross. It took a little poking, but now that it is done that code should be able to be re-used. 

You're probably not going to get a relationship quite like React and React Native (like, can't see rust mixed with react-native being a thing) so I think if you kept it to the react-fam that'll limit the scope somewhat.

@GantMan makes a good observation in terms of react dependencies so we'd have to nut that out but I can't see it being a show-stopper.

I'll watch the talk from chain react that Jamons referring to, but in the meantime  @kirakik  do you know of an example oss repo anywhere that does `react` and `react-native` ? I've not done it before as my web functions are distinctly different to my mobile ones.

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
