### ISSUE TITLE
React Native - bundling failed: Error: Unable to resolve module `http`

### ISSUE THREAD

**Issue by elango** [infinitered/ignite#1322]
error: bundling failed: Error: Unable to resolve module `http` from `/Volumes/{app}/node_modules/node-fetch/index.js`: Module `http` does not exist in the Haste module map

Anyidea how to resolve this?

Thanks

**Comment by nicholas** [comment]
Hey guys, I too am seeing this issue.

To try and isolate, I created a new react native app with `react-native init` and went about doing what I was doing with Ignite, installing and using [contentful.js](https://github.com/contentful/contentful.js). Instead of `http` being the module it couldn't resolve, I saw instead:
> Unable to resolve module `assert` from `/Users/.../node_modules/contentful/dist/contentful.node.js`: Module `assert` does not exist in the Haste module map

@elango Are/were you also adding a dependency when you got this error? My bet is on something tied to [Axios](https://github.com/axios/axios) if so.

Though it appears resolving `http` was successful in a blank app -- its require is above `assert` in the file doing the loading, I _think_ [here](https://github.com/axios/axios/blob/21ae22dbd3ae3d3a55d9efd4eead3dd7fb6d8e6e/test/unit/adapters/http.js#L2) -- it's not clear to me that this is an Ignite issue, though an expert angle would be appreciated. 😄

**Comment by nicholas** [comment]
To followup, the issue for me ended up being that the dependency I was importing had a `browser` variant that I was supposed to use that I guess handles core node libraries like `http` in a way that works. So, at least for me, this was not an Ignite issue nor Axios or even React Native for that matter. Just me. 🤦‍♂️
