### ISSUE TITLE
ignite app size is 30.2 mb 

### ISSUE THREAD

**Issue by affanhashone** [infinitered/ignite#1432]
why app size is so big 30.2 mb without any huge libraries ?

**Comment by kevinvangelder** [comment]
If memory serves, an empty Hello World React Native app is ~25MB. We haven't spent much time on optimizing bundle size because it isn't really an important factor for most of our clients. However, if someone wanted to do a breakdown on why the bundle is so large and/or some pull requests to reduce the initial size we'd be happy to take a look.

**Comment by affanhashone** [comment]
@kevinvangelder for your quick Response, I think after React Native 0.60 The App Size Will Reduce, But Still have a Look When Your Team Get Time. I can Use Android App Bundle To reduce the app size, But Ios Is a concern.

**Comment by jamonholmgren** [comment]
The Hermes Engine will further dramatically reduce package size on Android. I think over time this will improve. We'd love some help reducing app size!

**Comment by ferroblesh** [comment]
is there any current work to reduce the size? How may I help with that?

**Comment by nirre7** [comment]
@ferroblesh 

Our release build is about 11mb with a bunch of 3rd party libs.

Android: If you release the app as aab instead of apk then you'll reduce the size of the app a lot. 
To be able to do that you need to signup for "google app signing". 
There are several resources out there https://shift.infinite.red/handling-64-bit-android-builds-for-react-native-2fcd7a2e5c14

**Comment by mlaco** [comment]
Inside an Ignite project, is this the app whose size we're concerned with?`ios/build/TestAppSize/Build/Products/Release-iphonesimulator/TestAppSize.app`
 This was 22.1 MB for me.

**Comment by frankcalise** [comment]
This app bundle size topic has been discussed over at issues https://github.com/infinitered/ignite/issues/2240 and https://github.com/infinitered/ignite/issues/1947#issuecomment-1223985929 so I'm going to close this for now.

Closing this for now but feel free to bring it back up in [Discussions](https://github.com/infinitered/ignite/discussions) or [Community Slack](https://community.infinite.red/)
