### ISSUE TITLE
Why do "ignite new <project>" creates ".git" directory?

### ISSUE THREAD

**Issue by tayfunyasar** [infinitered/ignite#1459]
I tried 2 times to be sure. Why does ignite creates .git directory?

**Comment by ruddell** [comment]
It's the default for new Ignite apps.  You can pass `--skip-git` to `ignite new` to skip initializing a git repository, or delete the `.git` folder if you already started an app.

**Comment by kevinvangelder** [comment]
Git is a powerful (and industry-standard) version control system. It is included by default because the majority of users will want to use it with their app and it's more convenient for it to be done automatically for them. As ruddell mentioned above, you can easily skip git or remove it after you have generated your project.

**Comment by Jay-study-nildana** [comment]
At this point, I think, it can be safely assumed that most developers already know and use git. This simply adds an additional step to the entire process. 

I think that is the point @tayfunyasar was trying to make. 

I ran into the same problem because the ignite project was part of a monorepo that contains other projects, and the monorepo is already linked to GitHub. I was unable to add the ignite project, came here, found out that you were adding git by default. 

I suppose this helps new developers, like, developers who are new to react and also new to react native and also new to ignite and also new to git. That is a very small intersection on a Venn diagram, in my opinion :)
