### ISSUE TITLE
Generated boilerplate needs to be updated

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1485]
The boilerplate that is generated with `ignite plugin new ignite-my-boilerplate` is hopelessly out of date.

Link: https://github.com/infinitered/ignite/blob/master/src/templates/plugin

1. The React Native version is really old
2. It uses `context` rather than `toolbox`
3. It uses `parameters.third` [which is wrong](https://github.com/infinitered/ignite/blob/dd71788cdef0efa1ba880c2491a41c588c2d9ed5/src/templates/plugin/boilerplate.js.ejs#L30) (should be parameters.first)
4. It uses ava for testing rather than jest
5. No TypeScript support

This could really use some love!

**Comment by mlaco** [comment]
- [ ]  update RN version
- [ ]  change `context` to toolbox
- [ ]  Fix: It uses `parameters.third` [which is wrong](https://github.com/infinitered/ignite/blob/dd71788cdef0efa1ba880c2491a41c588c2d9ed5/src/templates/plugin/boilerplate.js.ejs#L30) (should be parameters.first)
- [ ]  Fix: It uses ava for testing rather than jest
- [ ]  Add typescript support

**Comment by bryanstearns** [comment]
Closing: as of the [Ignite Flame rewrite](https://github.com/infinitered/ignite/pull/1568), Ignite no longer supports plugins.
