### ISSUE TITLE
Error generating new app on Windows

### ISSUE THREAD

**Issue by patevs** [infinitered/ignite#1580]
Running `ignite new ignite_app` on windows produces the following error:

```bash
   🔥 Igniting app
   ☕️ Baking CocoaPods

C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^
yarn run v1.22.5
,error Command "format" not found.
,info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

---

Steps to reproduce

1. Run: `ignite new ignite_app`

**Comment by Chimpaya** [comment]
Yeah it's a problem with the format script in package.json. Change the single quote into double quote, using escape like this` \"`

**Comment by nirre7** [comment]
I ran into this one as well. I'm on a mac though.
Tried to update the format scripts but does not work..
Probably need to dig into this a bit more, when I have time...

**Comment by nirre7** [comment]
@patevs Make sure you don't have an old react-native-cli installation globally in npm, thats what I had 🤦 .

You can verify this by running
`npx react-native --version `
It should should start a download etc and state 4.13.1 or similar.

In my case it went really fast (i.e local install) and was a way older version..

**Comment by jerrybuks** [comment]
currently having the same issue

**Comment by nirre7** [comment]
@patevs @jerrybuks if you run 
`npx react-native --version`
What do you get?

**Comment by jerrybuks** [comment]
@patevs  I get 4.13.1

**Comment by nirre7** [comment]
> @nirre7 I get 4.13.1

Well thats weird. I got it working when removing my old version and got it working with 4.13.1.

**Comment by banerjed** [comment]
I am having the same issue on Mac -- I've tried half a dozen times with fresh installs of the overall installation, but am still facing this error. 

banerjed@Dhritimans-iMac work % ignite doctor
System
  platform           darwin                                               
  arch               x64                                                  
  cpu                4 cores      Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz 
  directory          work         /Users/banerjed/work                    

JavaScript
  node               15.4.0       /usr/local/bin/node            
  npm                7.0.15       /usr/local/bin/npm             
  yarn               1.22.5       /Users/banerjed/.yarn/bin/yarn 

Ignite
  ignite-cli         6.0.0        /Users/banerjed/.config/yarn/global/node_modules/.bin/ignite      
  ignite src         build        /Users/banerjed/.config/yarn/global/node_modules/ignite-cli/build 

Android
  java               1.8.0_275    /usr/bin/java                       
  android home       -            /Users/banerjed/Library/Android/sdk 

iOS
  xcode              12.3       
  cocoapods          1.10.0       /usr/local/bin/pod

**Comment by nirre7** [comment]
@banerjed @jerrybuks @patevs
Try to create an app with expo i.e 
`npx ignite-cli new PizzaApp --expo`

**Comment by nirre7** [comment]
@banerjed @jerrybuks @patevs
You could also try:
`npx -p ignite-cli new PizzaApp`

**Comment by jerrybuks** [comment]
@banerjed I'm not sure why this error, but after trying on my windows and it kept failing I decide to try generating the project on my linux (ubuntu)  and it worked once. My linux distro had no installation of react-native-cli or expo before,  so I guess you should try to uninstall expo and react-native-cli installed globally and just run

# for vanilla React Native
npx ignite-cli new PizzaApp

# or for Expo-powered:
npx ignite-cli new PizzaApp --expo

**Comment by nirre7** [comment]
Try (on mac)
`which react-native-cli`
If this is the usr/.../bin path then you need to remove the local install, since this might mess with the npx command and ignite-cli command

Also try 
`npx --ignore-existing ignite-cli new PizzaApp`

![image](https://user-images.githubusercontent.com/4352781/103556240-c539a780-4eb1-11eb-9ac7-24254759f7ba.png)

I think you get the "format error" since the template command to the react-native-cli init command didn't work, this means that the package.json from the boilerplate won't be "used" hence there is no format script in the package.json (which is from the react-native-cli "vanilla" install). 
You can verify this by looking into the folder you tried to init the ignite app.

**Comment by banerjed** [comment]
****banerjed@Dhritimans-iMac work % which react-native-cli**
react-native-cli not found**

**banerjed@Dhritimans-iMac work % npx --ignore-existing ignite-cli new PizzaApp**
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
   

   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating PizzaApp using Ignite 6.0.0
    █ Powered by Infinite Red - https://infinite.red
    █ Using react-native-cli
    ────────────────────────────────────────────────

   🔥 Igniting app

/Users/banerjed/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^
(node:43253) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
,npm, WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
,npm WARN deprecated har-validator@5.1.5: this library is no longer supported
,npm, ,WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
,node:fs:611
  handleErrorFromBinding(ctx);
  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:611:3)
    at tryReadSync (node:fs:385:20)
    at Object.readFileSync (node:fs:422:19)
    at copyAndReplace (/Users/banerjed/work/PizzaApp/node_modules/@react-native-community/cli/build/tools/copyAndReplace.js:102:33)
    at /Users/banerjed/work/PizzaApp/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:129:33
    at Array.forEach (<anonymous>)
    at copyProjectTemplateAndReplace (/Users/banerjed/work/PizzaApp/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:31)
    at createFromRemoteTemplate (/Users/banerjed/work/PizzaApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async createProjectFromTemplate (/Users/banerjed/work/PizzaApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
,npm, ERR!, code 1
,npm ,ERR! path /Users/banerjed/work
,npm ERR!, command failed
,npm ERR! command sh -c react-native init PizzaApp --template 'file:///Users/banerjed/.config/yarn/global/node_modules/ignite-cli'
,
,npm ERR! A complete log of this run can be found in:
npm, ERR!     /Users/banerjed/.npm/_logs/2021-01-04T17_04_21_368Z-debug.log

(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code 1
npm ERR! path /Users/banerjed/work
npm ERR! command failed
npm ERR! command sh -c ignite-cli new PizzaApp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/banerjed/.npm/_logs/2021-01-04T17_04_21_538Z-debug.log

**Comment by nirre7** [comment]
@banerjed 
Can you create a vanilla react-native project?
`npx react-native init AwesomeProject`

**Comment by nirre7** [comment]
FWIW here is my environment setup and I can create vanilla ignite js apps and with expo.

![image](https://user-images.githubusercontent.com/4352781/103622315-d2e54080-4f36-11eb-9e36-4cf0f4d77445.png)

**Comment by nirre7** [comment]
> npx: the --ignore-existing argument has been removed.
> See `npm help exec` for more information

I don't think it has been removed 🤔 
`npx --help` still lists it, and its still in the [npx repo](https://github.com/npm/npx#description)

**Comment by banerjed** [comment]
FYI -- after the upgrade to 6.1.0, my issues were resolved and I was able to create apps very cleanly. No clue how it it behaving on a Windows machine though...

**Comment by withewolf-dev** [comment]
> > @nirre7 I get 4.13.1
> 
> Well thats weird. I got it working when removing my old version and got it working with 4.13.1.
> 
> Try removing any local installs

When Not inside React Native Project it shows ** react-native-cli: 2.0.1**
when Inside a react native Project it shows ** version  4.13.1

**Comment by b3hz4d** [comment]
Check which version of Nodejs you are using with running `node -v`
I was using Nodejs version 14.15.3 (LTS) and then updated to latest version (15.5.1 Current) and now problem solved for me. :)

**Comment by brentkeller** [comment]
I'm on Windows and I was having this issue too (with Ignite 6.1.0). After installing node 15.5.1 it worked as expected, so that seems to do the trick.

**Comment by jamonholmgren** [comment]
I installed 14.15.3 and was able to spin up a new app with no problems. Not sure what's going on there. I am on macOS though. I'll try on Windows.

**Comment by jamonholmgren** [comment]
I'll keep doing research, but it looks like it's spinning up new apps fine after the above fix.

**Comment by jamonholmgren** [comment]
BTW, I tried with both Node 15 and 14 and both worked on my machine.

**Comment by b3hz4d** [comment]
> BTW, I tried with both Node 15 and 14 and both worked on my machine.

On Windows or MacOS

**Comment by jamonholmgren** [comment]
@b3hz4d Both versions on both OS's.

**Comment by jamonholmgren** [comment]
Here's my current `ignite doctor` (note: needs #1592 to run properly)

![image](https://user-images.githubusercontent.com/1479215/104416502-ca899880-5528-11eb-9703-34a7c614d7ba.png)

**Comment by jamonholmgren** [comment]
Going to call it a night, but if y'all have more context for me, hit me up here -- I'll take a look when I can!

**Comment by b3hz4d** [comment]
@jamonholmgren I tried it again with Node 14 and its seems npm is what causing this problem!
When I installed Node 15 npm v7.3.0 installed and it asked for installing new version 7.4.0, So I installed it globally.
After reinstalling Node 14 creating new app didn't have problem because of npm v7.4.0. Then I removed it and with version 6.14.10 the problem is back again
```
yarn run v1.22.5
$ npm-run-all format:*
$ prettier --write '**/*.js'
[error] No files matching the pattern were found: "'**/*.js'".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "format:js" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by b3hz4d** [comment]
@jamonholmgren Using double quote instead of single (your commit) fixed this error 👍

**Comment by dbeaugrand** [comment]
I was experiencing "throw up" issue too. I saw a comment earlier in the thread saying installing react-native-cli globally was not recommended. Once I removed it and reran npx --ignore-existing ignite-cli new myapp it worked as expected.

**Comment by jamonholmgren** [comment]
Would someone want to do a PR adding a warning if we detect that `react-native-cli` is already installed?

**Comment by MLDMoritz** [comment]
I still experience this under Linux subsystem under windows. Ubuntu:

```
console@WORKSTATION:~/projects/carapp$ ignite-cli new CarApp


   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating CarApp using Ignite 6.3.0
    █ Powered by Infinite Red - https://infinite.red
    █ Using react-native-cli
    ────────────────────────────────────────────────

   🔥 Igniting app



   🧊 Cooling print nozzles
   ☕️ Baking CocoaPods

/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^
yarn run v1.22.5
warning ../package.json: No license field
error Command "format" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by andrewlorenz** [comment]
does anyone have any idea how I can resolve this discrepancy (where is this other ignite-cli entry coming from ??!!)
![image](https://user-images.githubusercontent.com/7443883/111632430-6024fb00-87ec-11eb-9ab7-48bcc402da36.png)

**Comment by fahadOpine** [comment]
@MLDMoritz  please check if you have `react-native-cli ` installed by running `npm list -g react-native-cli` if so uninstall it by  `npm uninstall react-native-cli`. You should be good to go then.

**Comment by leotm** [comment]
Cheers ^ `brew remove react-native-cli` solved for me
