### ISSUE TITLE
Generating new app without expo have expo dependencies

### ISSUE THREAD

**Issue by b3hz4d** [infinitered/ignite#1595]
I  generated new app with ignite-cli v6.1.1 but I think there is some packages that is using with expo like:
```
"expo-localization": "^9.1.0",
"jest-expo": "^40.0.1",
"react-native-unimodules": "^0.11.0",
"@unimodules/core": "^6.0.0",
```
So is expo dependencies used and needed in project? 
---

Steps to reproduce

1. `npx ignite-cli new TestApp`

---

`ignite doctor` results:
```
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
  directory          Five         E:\Work\Projects\FiveFE\Five

JavaScript (and globally-installed packages)
  node               15.5.1       C:\Program Files\nodejs\node.EXE
  npm                7.3.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.22.5       C:\Program Files (x86)\Yarn\bin\yarn.CMD
    ignite-cli       6.1.1

Ignite
  ignite-cli         6.1.1        C:\Users\Edmond\AppData\Local\Yarn\bin\ignite.CMD
  ignite src         build        C:\Users\Edmond\AppData\Local\Yarn\Data\global\node_modules\ignite-cli\build

Android
  java               1.8.0_271    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\App\Android\sdk
```

**Comment by b3hz4d** [comment]
Even `app.json` is based on expo project

**Comment by jamonholmgren** [comment]
Thanks for asking, @b3hz4d! Three of those are indeed on purpose, while the other couple of things you mentioned should be fixed.

* @unimodules/core & react-native-unimodules - We are including Unimodules so you can include any of Expo's excellent packages in a non-Expo
* expo-localization - This package works in both Expo and non-Expo, so we unified on one package rather than supporting 2

We should delete `app.json` and not include `jest-expo` in our main package.json, though, so thanks for bringing that up. Want to do a PR to move `jest-expo` into the package.expo.json and add to the `new.ts` removing the `app.json`?

**Comment by jamonholmgren** [comment]
Note we would also need to remove the `"preset": "jest-expo"` from the package.json (and somehow add it back in, maybe in the Expo package.expo.json, if it merges properly).
