### ISSUE TITLE
Attempted to remove more RCTKeyboardObserver listeners than added

### ISSUE THREAD

**Issue by wkrause13** [infinitered/ignite#166]
To Reproduce:
1. Call the login component screen
2. Use the navigator to go back to the launch screen
3. Navigate back to the login screen
4. Use the navigator to go back to the launch screen

You should now see the error:
Attempted to remove more RCTKeyboardObserver listeners than added

![image](http://g.recordit.co/sVRqvUxPJY.gif)

**Comment by GantMan** [comment]
awesome find!  It seems if you hit back slowly, it works just fine.   You have to press back quickly.  This stinks of a Navigator issue, which is known for being strange when someone presses back at a quick pace.

I'm checking into this now.

**Comment by GantMan** [comment]
@wkrause13 - this should be fixed in https://github.com/infinitered/ignite/pull/167

Please verify this works for you, and I will merge this fix in master.

Additionally, I will not be updating our generated screens, as they will soon be migrated to using the keyboard spacer component.  So this is the only place that matters for now.

**Comment by GantMan** [comment]
closing this ticket.  Will reopen if #167 proves false.

**Comment by sibelius** [comment]
it could be related to https://github.com/facebook/react-native/issues/12223 on RN42

**Comment by skellock** [comment]
@sibelius - this issue predates 0.42 by a bit.  But I didn't know that was an issue.  Thanks for pointing that out.  Appreciate that.
