### ISSUE TITLE
Newly created app from boilerplate crashes (Expo-powered)

### ISSUE THREAD

**Issue by InderdeepBajwa** [infinitered/ignite#1670]
What's going on?
---
This started happening since today (was OK yesterday) that a new Expo project initiation using `npx ignite-cli new PizzaApp --expo` causes a memory leak in both iOS and Android on the homescreen. Nothing works when in the Expo app. The homescreen freezes and eventually crashes.

Again, I replicated the exact steps ~30 hours ago to create a new project from boilerplate and it worked.

Video of RAM usage:
https://user-images.githubusercontent.com/20612193/116774509-02aadd80-aa2b-11eb-8363-3a09c3f51e7f.mov

Steps to reproduce

1. Run `npx ignite-cli new PizzaApp --expo` to create a new project.
2. cd into the project. Run `yarn start` or `expo start`
3. Scan the QR code and launch the boilerplate in Expo app.
4. Wait for the application to crash. (Boilerplate in Expo at this point is not usable at all. Nothing works)

---

`ignite doctor` results:
System
  platform           win32
  arch               x64
  cpu                8 cores          Intel(R) i7-7700HQ CPU
  directory          <Project Title>   <directory path>

JavaScript (and globally-installed packages)
  node               14.16.0      C:\Program Files\nodejs\node.EXE
  npm                6.14.11      C:\Program Files\nodejs\npm.CMD
    expo-cli         4.4.3
  yarn               1.22.5       C:\Program Files (x86)\Yarn\bin\yarn.CMD

Ignite
  ignite-cli         6.10.0       %AppData%\Roaming\npm-cache\_npx\3612\ignite.CMD
  ignite src         build        %AppData%\Roaming\npm-cache\_npx\3612\node_modules\ignite-cli\build

Android
  java               1.8.0_291    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            undefined

**Comment by gpolek** [comment]
Same here. Bootstraped today using `npx ignite-cli new XYZ --expo` and RAM increases all the time and app crashes after a while due to OOM.

**Comment by conan60** [comment]
Same here.
`System
  platform           linux                                                               
  arch               x64                                                                 
  cpu                4 cores             Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz 
  directory          covoiturageMobile   /home/dell/Downloads/PFE3GLSI/covoiturageMobile 

JavaScript (and globally-installed packages)
  node                 14.16.1      /usr/local/bin/node 
  npm                  7.11.2       /usr/local/bin/npm  
    @ionic/cli         6.11.11                          
    create-react-app   3.4.1                            
    expo-cli           4.4.3                            
    ignite-cli         6.9.1                            
    n                  7.2.2                            
    npm                7.11.2                           
    stable             0.1.8                            
  yarn                 -            not installed       

Ignite
  ignite-cli         6.9.1        /usr/local/bin/ignite                        
  ignite src         build        /usr/local/lib/node_modules/ignite-cli/build 

Android
  java               -            null      
  android home       -            undefined `

**Comment by nirre7** [comment]
Try with npm 6.x

**Comment by nirre7** [comment]
Could be that expo does not support RN 64.x officially (afaik) which is included in Ignite.

**Comment by gpolek** [comment]
Well, I don't think so. Accordingly to my package.json RN used during bootstrap is 0.63

```shell
$ cat package.json | jq .dependencies | grep react-native
  "@react-native-async-storage/async-storage": "^1.14.1",
  "@react-native-community/masked-view": "0.1.10",
  "react-native": "~0.63.4",
  "react-native-gesture-handler": "1.10.3",
  "react-native-keychain": "6.2.0",
  "react-native-reanimated": "~1.13.0",
  "react-native-safe-area-context": "3.1.9",
  "react-native-screens": "2.18.1",
  "react-native-splash-screen": "3.2.0",
  "react-native-unimodules": "~0.12.0",
  "react-native-web": "~0.13.12",
  "reactotron-react-native": "5.0.0",
```

**Comment by nirre7** [comment]
Thats good, that we don't override the version.

**Comment by mazenchami** [comment]
@InderdeepBajwa can you please try this with the latest version of Ignite (6.12.2)? I was able to use this new version to create a demo app following your steps and have it open while monitoring the RAM and not seeing any large spikes that caused the app to crash.

**Comment by InderdeepBajwa** [comment]
@mazenchami : Will try this in the morning and let you know :)

**Comment by wilmanh** [comment]
Hi i have a similar problem when i try to create a new app (but worst)
`npx --ignore-existing ignite-cli new TrainLogApp --expo --overwrite --debug --npm                                                                                                   ~/code/myProjects

npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
 [object Object]


   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating TrainLogApp using Ignite 7.0.5
    █ Powered by Infinite Red - https://infinite.red
    █ Using expo-cli
    ────────────────────────────────────────────────

 [object Object]
    ⠋ Igniting app npx expo-cli init TrainLogApp --template /Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/boilerplate --non-interactive
    🔥 Igniting app
 - Downloading and extracting project files.

 ✔ Downloaded and extracted project files.

 [22:54:38] 🧶 Using Yarn to install packages. Pass --npm to use npm instead.

    ⠋ Summoning Expo CLI - Installing JavaScript dependencies.

    ⠴ Summoning Expo CLI > yarn install

    ⠧ Summoning Expo CLI yarn install v1.22.10

    ⠇ Summoning Expo CLI info No lockfile found.

 [1/4] Resolving packages...

    ⠙ Summoning Expo CLI [2/4] Fetching packages...

    ⠇ Summoning Expo CLI [3/4] Linking dependencies...

    ⠋ Summoning Expo CLI [4/4] Building fresh packages...

    ⠹ Summoning Expo CLI success Saved lockfile.

    ⠼ Summoning Expo CLI $ node ./bin/postInstall

    ⠹ Summoning Expo CLI patch-package 6.2.2

 Applying patches...

    ⠏ Summoning Expo CLI

 ✔︎ Solidarity checks valid

    ⠏ Summoning Expo CLI Jetifier found 1263 file(s) to forward-jetify. Using 4 workers...

    ⠸ Summoning Expo CLI Installing unimodules:
 expo-constants@9.3.5 from ../node_modules/expo-constants/ios
 expo-file-system@9.3.0 from ../node_modules/expo-file-system/ios
 expo-image-loader@1.3.0 from ../node_modules/expo-image-loader/ios
 expo-localization@9.1.0 from ../node_modules/expo-localization/ios
 expo-permissions@10.0.0 from ../node_modules/expo-permissions/ios
 unimodules-app-loader@1.4.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@5.4.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.4.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.4.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@6.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.4.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.4.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.4.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.4.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.4.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.7.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.4.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.4.0 from ../node_modules/unimodules-task-manager-interface/ios


    ⠧ Summoning Expo CLI Auto-linking React Native modules for target `TrainLogApp`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNKeychain, RNScreens, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`

 Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`

    ⠏ Summoning Expo CLI Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

    ⠼ Summoning Expo CLI [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.9.1`.

    ⠴ Summoning Expo CLI info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    ⠦ Summoning Expo CLI ✖ Something went wrong installing JavaScript dependencies. Check your yarn logs. Continuing to initialize the app.
- Installing CocoaPods...

    ⠹ Summoning Expo CLI 1.9.1

 > pod install

    ⠸ Summoning Expo CLI Installing unimodules:
 expo-constants@9.3.5 from ../node_modules/expo-constants/ios
 expo-file-system@9.3.0 from ../node_modules/expo-file-system/ios
 expo-image-loader@1.3.0 from ../node_modules/expo-image-loader/ios
 expo-localization@9.1.0 from ../node_modules/expo-localization/ios
 expo-permissions@10.0.0 from ../node_modules/expo-permissions/ios
 unimodules-app-loader@1.4.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@5.4.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.4.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.4.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@6.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.4.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.4.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.4.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.4.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.4.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.7.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.4.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.4.0 from ../node_modules/unimodules-task-manager-interface/ios


    ⠼ Summoning Expo CLI Auto-linking React Native modules for target `TrainLogApp`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNKeychain, RNScreens, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`

 Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`

    ⠦ Summoning Expo CLI Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

    ⠏ Summoning Expo CLI [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.9.1`.

 ⚠️  Something went wrong running `pod install` in the `ios` directory.
[22:57:54] Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
[!] The version of CocoaPods used to generate the lockfile (1.10.1) is higher than the version of the current executable (1.9.1). Incompatibility issues may arise.


✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd TrainLogApp
- yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- yarn android
- yarn ios
- yarn web

⚠️  Before running your app on iOS, make sure you have CocoaPods installed and initialize the project:

  cd TrainLogApp/
  npx pod-install


    🪔 Summoning Expo CLI
    🎫 Cleaning up Expo install
 /Users/someUser/code/myProjects
 /Users/someUser/code/myProjects/TrainLogApp/.gitignore
 /Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/boilerplate/.npmignore
    ⠦ Unboxing NPM dependencies patch-package 6.2.2

    ⠧ Unboxing NPM dependencies Applying patches...

    ⠹ Unboxing NPM dependencies

 ✔︎ Solidarity checks valid

    ⠋ Unboxing NPM dependencies Jetifier found 1410 file(s) to forward-jetify. Using 4 workers...

    🧶 Unboxing NPM dependencies
    ⠇  Writing your app name in the sand Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same.

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

    ⠏  Writing your app name in the sand Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 Ignore above error if this file doesn't exist

 /package.json MODIFIED

 /app.json MODIFIED

    ⠧  Writing your app name in the sand /app.json MODIFIED

    ⠇  Writing your app name in the sand
/Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-tvOS
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-tvOSTests
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj/xcshareddata/xcschemes/TrainLogApp-tvOS.xcscheme
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj/xcshareddata/xcschemes/TrainLogApp.xcscheme
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogAppTests
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogAppTests/TrainLogAppTests.m
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcworkspace
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp/TrainLogApp.entitlements
mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-Bridging-Header.h
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/Users/someUser/code/myProjects/TrainLogApp/android/app/src/main/AndroidManifest.xml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/someUser/code/myProjects/TrainLogApp/android/app/src/main/AndroidManifest.xml'
}

(Use `node --trace-uncaught ...` to show where the exception was thrown)`

`System
  platform           darwin
  arch               x64
  cpu                4 cores      Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  directory          myProjects   /Users/someUser/code/myProjects

JavaScript
  node               15.2.1       /Users/someUser/.nvm/versions/node/v15.2.1/bin/node
  npm                7.19.1       /Users/someUser/.nvm/versions/node/v15.2.1/bin/npm
  yarn               1.22.10      /usr/local/bin/yarn

Ignite
  ignite-cli         7.0.5        /Users/someUser/.nvm/versions/node/v15.2.1/bin/ignite
  ignite src         build        /Users/someUser/.config/yarn/global/node_modules/ignite-cli/build
  generators         {}

Android
  java               1.8.0_222    /usr/bin/java
  android home       -            /Users/someUser/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.9.1        /usr/local/bin/pod`

i look and the folders android or ios does not exists..... i am upgrading cocoapods right now to verifiy if thats the problem

**Comment by wilmanh** [comment]
> Hi i have a similar problem when i try to create a new app (but worst)
> `npx --ignore-existing ignite-cli new TrainLogApp --expo --overwrite --debug --npm ~/code/myProjects
> 
> npx: the --ignore-existing argument has been removed.
> See `npm help exec` for more information
> [object Object]
> 
> · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·
> 
> ```
> █ Creating TrainLogApp using Ignite 7.0.5
> █ Powered by Infinite Red - https://infinite.red
> █ Using expo-cli
> ────────────────────────────────────────────────
> ```
> 
> [object Object]
> ⠋ Igniting app npx expo-cli init TrainLogApp --template /Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/boilerplate --non-interactive
> 🔥 Igniting app
> 
> * Downloading and extracting project files.
> 
> ✔ Downloaded and extracted project files.
> 
> [22:54:38] 🧶 Using Yarn to install packages. Pass --npm to use npm instead.
> 
> ```
> ⠋ Summoning Expo CLI - Installing JavaScript dependencies.
> 
> ⠴ Summoning Expo CLI > yarn install
> 
> ⠧ Summoning Expo CLI yarn install v1.22.10
> 
> ⠇ Summoning Expo CLI info No lockfile found.
> ```
> 
> [1/4] Resolving packages...
> 
> ```
> ⠙ Summoning Expo CLI [2/4] Fetching packages...
> 
> ⠇ Summoning Expo CLI [3/4] Linking dependencies...
> 
> ⠋ Summoning Expo CLI [4/4] Building fresh packages...
> 
> ⠹ Summoning Expo CLI success Saved lockfile.
> 
> ⠼ Summoning Expo CLI $ node ./bin/postInstall
> 
> ⠹ Summoning Expo CLI patch-package 6.2.2
> ```
> 
> Applying patches...
> 
> ```
> ⠏ Summoning Expo CLI
> ```
> 
> ✔︎ Solidarity checks valid
> 
> ```
> ⠏ Summoning Expo CLI Jetifier found 1263 file(s) to forward-jetify. Using 4 workers...
> 
> ⠸ Summoning Expo CLI Installing unimodules:
> ```
> 
> expo-constants@9.3.5 from ../node_modules/expo-constants/ios
> expo-file-system@9.3.0 from ../node_modules/expo-file-system/ios
> expo-image-loader@1.3.0 from ../node_modules/expo-image-loader/ios
> expo-localization@9.1.0 from ../node_modules/expo-localization/ios
> expo-permissions@10.0.0 from ../node_modules/expo-permissions/ios
> unimodules-app-loader@1.4.0 from ../node_modules/unimodules-app-loader/ios
> unimodules-barcode-scanner-interface@5.4.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
> unimodules-camera-interface@5.4.0 from ../node_modules/unimodules-camera-interface/ios
> unimodules-constants-interface@5.4.0 from ../node_modules/unimodules-constants-interface/ios
> unimodules-core@6.0.0 from ../node_modules/@unimodules/core/ios
> unimodules-face-detector-interface@5.4.0 from ../node_modules/unimodules-face-detector-interface/ios
> unimodules-file-system-interface@5.4.0 from ../node_modules/unimodules-file-system-interface/ios
> unimodules-font-interface@5.4.0 from ../node_modules/unimodules-font-interface/ios
> unimodules-image-loader-interface@5.4.0 from ../node_modules/unimodules-image-loader-interface/ios
> unimodules-permissions-interface@5.4.0 from ../node_modules/unimodules-permissions-interface/ios
> unimodules-react-native-adapter@5.7.0 from ../node_modules/@unimodules/react-native-adapter/ios
> unimodules-sensors-interface@5.4.0 from ../node_modules/unimodules-sensors-interface/ios
> unimodules-task-manager-interface@5.4.0 from ../node_modules/unimodules-task-manager-interface/ios
> 
> ```
> ⠧ Summoning Expo CLI Auto-linking React Native modules for target `TrainLogApp`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNKeychain, RNScreens, and react-native-safe-area-context
> ```
> 
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> 
> Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
> 
> ```
> ⠏ Summoning Expo CLI Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> 
> ⠼ Summoning Expo CLI [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.9.1`.
> 
> ⠴ Summoning Expo CLI info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> ⠦ Summoning Expo CLI ✖ Something went wrong installing JavaScript dependencies. Check your yarn logs. Continuing to initialize the app.
> ```
> 
> * Installing CocoaPods...
>   ⠹ Summoning Expo CLI 1.9.1
> 
> > pod install
> 
> ```
> ⠸ Summoning Expo CLI Installing unimodules:
> ```
> 
> expo-constants@9.3.5 from ../node_modules/expo-constants/ios
> expo-file-system@9.3.0 from ../node_modules/expo-file-system/ios
> expo-image-loader@1.3.0 from ../node_modules/expo-image-loader/ios
> expo-localization@9.1.0 from ../node_modules/expo-localization/ios
> expo-permissions@10.0.0 from ../node_modules/expo-permissions/ios
> unimodules-app-loader@1.4.0 from ../node_modules/unimodules-app-loader/ios
> unimodules-barcode-scanner-interface@5.4.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
> unimodules-camera-interface@5.4.0 from ../node_modules/unimodules-camera-interface/ios
> unimodules-constants-interface@5.4.0 from ../node_modules/unimodules-constants-interface/ios
> unimodules-core@6.0.0 from ../node_modules/@unimodules/core/ios
> unimodules-face-detector-interface@5.4.0 from ../node_modules/unimodules-face-detector-interface/ios
> unimodules-file-system-interface@5.4.0 from ../node_modules/unimodules-file-system-interface/ios
> unimodules-font-interface@5.4.0 from ../node_modules/unimodules-font-interface/ios
> unimodules-image-loader-interface@5.4.0 from ../node_modules/unimodules-image-loader-interface/ios
> unimodules-permissions-interface@5.4.0 from ../node_modules/unimodules-permissions-interface/ios
> unimodules-react-native-adapter@5.7.0 from ../node_modules/@unimodules/react-native-adapter/ios
> unimodules-sensors-interface@5.4.0 from ../node_modules/unimodules-sensors-interface/ios
> unimodules-task-manager-interface@5.4.0 from ../node_modules/unimodules-task-manager-interface/ios
> 
> ```
> ⠼ Summoning Expo CLI Auto-linking React Native modules for target `TrainLogApp`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNKeychain, RNScreens, and react-native-safe-area-context
> ```
> 
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> 
> Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
> 
> ```
> ⠦ Summoning Expo CLI Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> 
> ⠏ Summoning Expo CLI [!] `React` requires CocoaPods version `>= 1.10.1`, which is not satisfied by your current version, `1.9.1`.
> ```
> 
> ⚠️ Something went wrong running `pod install` in the `ios` directory.
> [22:57:54] Command `pod install` failed.
> └─ Cause: pod exited with non-zero code: 1
> Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
> [!] The version of CocoaPods used to generate the lockfile (1.10.1) is higher than the version of the current executable (1.9.1). Incompatibility issues may arise.
> 
> ✅ Your project is ready!
> 
> To run your project, navigate to the directory and run one of the following yarn commands.
> 
> * cd TrainLogApp
> * yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
> * yarn android
> * yarn ios
> * yarn web
> 
> ⚠️ Before running your app on iOS, make sure you have CocoaPods installed and initialize the project:
> 
> cd TrainLogApp/
> npx pod-install
> 
> ```
> 🪔 Summoning Expo CLI
> 🎫 Cleaning up Expo install
> ```
> 
> /Users/someUser/code/myProjects
> /Users/someUser/code/myProjects/TrainLogApp/.gitignore
> /Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/boilerplate/.npmignore
> ⠦ Unboxing NPM dependencies patch-package 6.2.2
> 
> ```
> ⠧ Unboxing NPM dependencies Applying patches...
> 
> ⠹ Unboxing NPM dependencies
> ```
> 
> ✔︎ Solidarity checks valid
> 
> ```
> ⠋ Unboxing NPM dependencies Jetifier found 1410 file(s) to forward-jetify. Using 4 workers...
> 
> 🧶 Unboxing NPM dependencies
> ⠇  Writing your app name in the sand Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same.
> ```
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> ```
> ⠏  Writing your app name in the sand Ignore above error if this file doesn't exist
> ```
> 
> Ignore above error if this file doesn't exist
> 
> Ignore above error if this file doesn't exist
> 
> /package.json MODIFIED
> 
> /app.json MODIFIED
> 
> ```
> ⠧  Writing your app name in the sand /app.json MODIFIED
> 
> ⠇  Writing your app name in the sand
> ```
> 
> /Users/someUser/.nvm/versions/node/v15.2.1/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
> throw up;
> ^
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-tvOS
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-tvOSTests
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj/xcshareddata/xcschemes/TrainLogApp-tvOS.xcscheme
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcodeproj/xcshareddata/xcschemes/TrainLogApp.xcscheme
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogAppTests
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogAppTests/TrainLogAppTests.m
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp.xcworkspace
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp/TrainLogApp.entitlements
> mv: no such file or directory: /Users/someUser/code/myProjects/TrainLogApp/ios/TrainLogApp-Bridging-Header.h
> node:internal/process/promises:218
> triggerUncaughtException(err, true /* fromPromise */);
> ^
> 
> [Error: ENOENT: no such file or directory, open '/Users/someUser/code/myProjects/TrainLogApp/android/app/src/main/AndroidManifest.xml'] {
> errno: -2,
> code: 'ENOENT',
> syscall: 'open',
> path: '/Users/someUser/code/myProjects/TrainLogApp/android/app/src/main/AndroidManifest.xml'
> }
> 
> (Use `node --trace-uncaught ...` to show where the exception was thrown)`
> 
> `System
> platform darwin
> arch x64
> cpu 4 cores Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
> directory myProjects /Users/someUser/code/myProjects
> 
> JavaScript
> node 15.2.1 /Users/someUser/.nvm/versions/node/v15.2.1/bin/node
> npm 7.19.1 /Users/someUser/.nvm/versions/node/v15.2.1/bin/npm
> yarn 1.22.10 /usr/local/bin/yarn
> 
> Ignite
> ignite-cli 7.0.5 /Users/someUser/.nvm/versions/node/v15.2.1/bin/ignite
> ignite src build /Users/someUser/.config/yarn/global/node_modules/ignite-cli/build
> generators {}
> 
> Android
> java 1.8.0_222 /usr/bin/java
> android home - /Users/someUser/Library/Android/sdk
> 
> iOS
> xcode 12.4
> cocoapods 1.9.1 /usr/local/bin/pod`
> 
> i look and the folders android or ios does not exists..... i am upgrading cocoapods right now to verifiy if thats the problem

 i just update the cocoapods but the error remains

**Comment by InderdeepBajwa** [comment]
New app is functioning normally for me. My issue is resolved. Not sure about the new reports and if they are linked to the original issue or not.
