### ISSUE TITLE
Anti-pattern on MST asynchronous action for Character Model

### ISSUE THREAD

**Issue by afbarbaro** [infinitered/ignite#1716]
What's going on?
The code provided in `getCharacters` action inside `character-store` uses `async await`.  Shouldn't this be using the generator pattern as described in the MST documentation for asynchronous actions?  The use of `async/await` is explicitly called out as not working properly for all cases and therefore not recommended.

MST documentation 
- https://mobx-state-tree.js.org/concepts/async-actions#using-generators
- https://mobx-state-tree.js.org/concepts/async-actions#what-about-async-await

Ignite Code
https://github.com/infinitered/ignite/blob/e905dbf47103430ec06b541297c79d7c5a7b4137/boilerplate/app/models/character-store/character-store.ts#L23

---

Steps to reproduce

1. N/A.

---

`ignite doctor` results:

**Comment by jamonholmgren** [comment]
@afbarbaro You're right in the general case, but what we do is we avoid setting anything directly in an async action and instead use setter actions, like this:

https://github.com/infinitered/ignite/blob/e905dbf47103430ec06b541297c79d7c5a7b4137/boilerplate/app/models/character-store/character-store.ts#L26

Because of that, there's no issues. In fact, there's no effective difference between using a `flow` and an async action _if_ you ensure you always call actions from inside the async action rather than trying to set any properties directly.

**Comment by afbarbaro** [comment]
Thank you, this makes sense to me now.  I appreciate your help!
