### ISSUE TITLE
React Navigation 6.x migration

### ISSUE THREAD

**Issue by softshipper** [infinitered/ignite#1753]
Hi all 
Please replace React Navigation 5.x through React Navigation 6.x.

Best regards,
Softshipper

**Comment by markrickert** [comment]
Hey @softshipper, react-navigation 6 is on the roadmap. This is a community project and we welcome pull requests! Please feel free to implement it and submit a pull request if you need it immediately. 

No need to open duplicate issues since you already requested this and @jamonholmgren responded in #1751. Now that #1712 has been merged, i'd anticipate that the react-navigation 6.0 upgrade will be pretty painless.

**Comment by softshipper** [comment]
Thanks so much for clarification.
