### ISSUE TITLE
Splash Screen label should match ignited app name

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#1766]
Regardless of the name of the ignited app, the splash screen is set to "RnDiffApp"

<img width="434" alt="Screen Shot 2021-08-12 at 11 40 38 AM" src="https://user-images.githubusercontent.com/144869/129251012-79b5ab54-2b76-417d-a835-588386c75c91.png">

See `LaunchScreen.storyboard` : 

`<label opaque="NO" clipsSubviews="YES" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="RnDiffApp" textAlignment="center" lineBreakMode="middleTruncation" baselineAdjustment="alignBaselines" minimumFontSize="18" translatesAutoresizingMaskIntoConstraints="NO" id="GJd-Yh-RWb">`

The text should be set to the name of the ignited app.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by dannyhw** [comment]
I think this can be closed since it looks like this is already handled by react-native-rename here: https://github.com/infinitered/ignite/blob/c561e6afead1470abe1bb6f4925df11a689efc2f/src/commands/new.ts#L257

**Comment by mazenchami** [comment]
@derekgreenberg thanks for logging this issue. Currently in Ignite v7.13.1, this issue is fixed, see attached image. Closing this issue.

![Simulator Screen Shot - iPhone 13 - 2022-06-27 at 12 14 38](https://user-images.githubusercontent.com/9324607/175988179-cd26abbc-ea2b-4ef9-9695-4179041ceb07.png)

@himanshu007-creator thank you very much for offering to work on this issue. Its currently resolved, but in the future if you're interested in helping support Ignite, please submit a PR and we'll take a look at it!
