### ISSUE TITLE
[Security] update transitive dependency ejs to latest version

### ISSUE THREAD

**Issue by terryatgithub** [infinitered/ignite#1922]
please consider to update gluegun to latest version to fix the following security issue:
https://github.com/mde/ejs/pull/573

**Comment by joshuayoes** [comment]
This would be better filed on the [gluegun](https://github.com/infinitered/gluegun) repository. 

This security issue doesn't really apply to our use of `ejs` in Gluegun because we are running our own template code only for the cli users host machine, not on a web server. This is an issue for ejs because users of websites could potentially inject and execute malicious code on web servers that they should not have access to. However, since we only run cli code on the users host machine, there is no target to try to gain elevated privileges on.
