### ISSUE TITLE
Does ignite work on windows 

### ISSUE THREAD

**Issue by thdave** [infinitered/ignite#196]
Hi

Can I install ignite on windows ?  Im on windows  10.  
I have the latest node version installed v.4.4.6
I run pm install -g react-native-ignite
I get the following errors 

C:>npm i -g react-native-ignite
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Dav\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "i" "-g" "react-native-ignite"
npm ERR! node v4.4.6
npm ERR! npm  v2.14.2
npm ERR! path C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json.501d40d20df7a598484440b222a7f543
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json.501d40d20df7a598484440b222a7f543' -> 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json.501d40d20df7a598484440b222a7f543' -> 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json.501d40d20df7a598484440b222a7f543',
npm ERR!   dest: 'C:\Users\Dav\AppData\Roaming\npm-cache\pinkie-promise\2.0.1\package\package.json',
npm ERR!   parent: 'find-up' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log////////////////////////////////////////

So I tried 
1. Open cmd as admin and run again - same issues
2 Open as admin and np                                                m cache clean -same issues
 Also my nam is working for other installs I use it all the time .
Any help grateful received , Ignite looks awesome I would really like to get going with it.

**Comment by GantMan** [comment]
@kevinvangelder  - is currently our Windows expert.  He's going to look into this soon.   

I have a Windows 10 machine as well, so I'll look into it along side him.  Though, I've been on mac for the past 6 years, so I'm going to be the slowest help.

**Comment by GantMan** [comment]
Co-locating all windows 10 information into one ticket:
* https://github.com/infinitered/ignite/issues/91 - This is a good one!
* https://github.com/infinitered/ignite/issues/214
* #144 
* #204

**Comment by cfogelklou** [comment]
The only issue I had when installing on Windows was that I had to manually install yo (it didn't prompt and install automatically like on OSX.)  Other than that, I created 3 projects in a row without fail.

**Comment by RianOQuill** [comment]
I have had the same issue. Here is my log:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-ignite"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\Woods\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.4d2399984763a6d26e8254747ee5170d
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Woods\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.4d2399984763a6d26e8254747ee5170d' -> 'C:\Users\Woods\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Woods\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json.4d2399984763a6d26e8254747ee5170d' -> 'C:\Users\Woods\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Woods\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json.4d2399984763a6d26e8254747ee5170d',
npm ERR!   dest: 'C:\\Users\\Woods\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json',
npm ERR!   parent: 'glob' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

I have:

1) Closed any and all editors, text or otherwise.
2) Disabled my anti-virus
3) Cleared my npm cache
4) Tried running the cmd line as admin and non admin roles

but I am still having this problem. I will restart my machine completely and see if this fixes the issue.

**Comment by greatbsky** [comment]
I think it's Yes, I start up on windows 7. After commands:
npm install -g react-native-ignite
npm install --global yo
npm install -g react-native-cli
ignite new IgniteTest
cd IgniteTest
react-native run-android

**Comment by ottotsuma** [comment]
C:\Users\"User"\Desktop\Textables>ignite new IgniteApp
This command requires yo to be installed.
Installing yo...
'CI' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
🔥 Setting IgniteApp on FIRE! 🔥
'yo' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
events.js:288
      throw er; // Unhandled 'error' event
      ^


This is the error message I got when trying to run "ignite new IgniteApp" in the cmd. I have no idea what the funky ?? are but the Japanese below is expected. Oh I should add I installed Ignite. 

C:\Users\"User"\Desktop\Textables\TextArt>ignite -V
1.13.0

Hope this helps also,

Snow
