### ISSUE TITLE
Expo CLI v5 issue

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1960]
I'd like to upgrade Ignite CLI to use expo-cli version 5.x, but I ran into an issue with Expo and using a local template. This is to track that issue.

https://github.com/expo/expo-cli/issues/4423

**Comment by frankcalise** [comment]
For what it's worth, if you use expo-cli@5.0.0 via npx definied in `new.ts` AND uninstall any globally installed expo-cli, a project does get created properly. For example:

```
const deps: { [k: string]: string } = {
  // expo-cli v5 would be nice, but we're having a problem with it:
  // https://github.com/expo/expo-cli/issues/4423
  expo: "5.0.0",
  podInstall: "0.1",
}
```

along with these dependencies in the package.expo.json boilerplate:

```
"dependencies": {
    "@expo/webpack-config": "^0.12.71",
    "expo-linear-gradient": "~11.3.0",
    "expo-localization": "~13.0.0",
    "expo-modules-core": "~0.9.2",
    "expo-status-bar": "~1.3.0",
    "expo": "~45.0.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native": "0.68.2",
    "react": "17.0.2"
  },
```

But then after `cd myproject`, `yarn start` you obviously get prompted to install expo-cli since it isn't available. Installing the latest then is just fine and ignite will open up to the demo screen.

However, defining it only as "5" will take the latest version and I do get that template error.

```
const deps: { [k: string]: string } = {
  // expo-cli v5 would be nice, but we're having a problem with it:
  // https://github.com/expo/expo-cli/issues/4423
  expo: "5",
  podInstall: "0.1",
}
```

Not sure if making use of the [Versioned Expo CLI](https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656) will be of help here, but it is still experimental AFAIK.

**Comment by jamonholmgren** [comment]
Let's work on Expo / Vanilla unification (#1983), which should solve this issue.

**Comment by frankcalise** [comment]
This is resolved with the unification of the boilerplate.

PR #1985 

Will be released in [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19)
