### ISSUE TITLE
React Native 0.69 / React 18

### ISSUE THREAD

**Issue by mkcode** [infinitered/ignite#1979]
Hi, Quick question. I am starting a new react-native project and am noticing that the ignite-cli is a little behind the current react-native version.

I'd love to start my new project using both the ignite-cli and React 18 / React-Native 0.69: https://reactnative.dev/docs/react-18-and-react-native

Are there any blocking issues preventing this update? Any clues as to the release schedule for this?

Thank you

**Comment by jamonholmgren** [comment]
Hey @mkcode! We just haven't started on the migration yet, no major issues I'm aware of yet.

One of the things we do with Ignite is make sure that we've done client migrations before we move Ignite over. This ensures that we know all the pitfalls of the newest versions. That's in-progress on a few projects, so stay tuned.

Once we do migrate Ignite, if you've used the _current_ version of Ignite and want to upgrade, the Ignite upgrade repo by @nirre7  is a great place to see what we did:

https://github.com/nirre7/ignite-diff-purge

**Comment by mkcode** [comment]
Thanks so much for the quick reply @jamonholmgren!

For what it is worth, I attempted to do a naive upgrade to 0.69.1 starting by running `npx react-native upgrade 0.69.1`

It went fairly smoothly until compiling the expo sdk, which appears to be blocker: https://docs.expo.dev/versions/latest/. It looks they are working on this as we speak: https://github.com/expo/expo/tree/sdk-46. Should be updated soon!

**Comment by jamonholmgren** [comment]
This will be a part of our Ignite v8: Maverick efforts.

**Comment by frankcalise** [comment]
@mkcode Hey - were you looking to contribute this change or just raising it to our attention? Let me know so we can assign it properly. Thanks!

**Comment by frankcalise** [comment]
> Aside from updating it to Expo v46, the ignite client drops Expo down to v43 even though that's not what's downloaded in the package.json from the boilerplate.
> 
> It's odd. The relevance here is that Expo Go now requires v44+.

Hi @JosephDunivan - the difference here is that if you build a vanilla react-native application, Expo v46 is included. Due to an issue with `expo-cli`, we haven't been able to update initializing a new Expo only app to v46. So currently when igniting an app project with `--expo`, the SDK is only at v43.

However, we've been reworking the `ignite-cli new` command to fix this issue and in this latest release, v8 Maverick (#1987) it won't be behind anymore.

My suggestion to you is that if you need to spin up a new Expo project right now via ignite, is to do so and then run `expo-cli upgrade` to bring it up to 46 (or anything 44-46). That way you can use Expo Go + ignite.

Hope that helps!

**Comment by frankcalise** [comment]
Resolved in #2003 - will be released in [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19)
