### ISSUE TITLE
Docs: Monorepo setup guide

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1981]
I'd like to add a monorepo setup guide to Ignite's docs. It's a common request these days, and is not a straightforward process (took us a week recently on one client's project).

It would live in `./docs/Monorepo-Setup-Guide.md` most likely.

cc @kevinvangelder @leonskim

**Comment by flexbox** [comment]
In the last few months, I think I have explored all the possible solutions to create a monorepo with react native.

My 2 cents on this:

1. https://github.com/flexbox/react-native-nextjs-monorepo `expo` + `nextjs`
used https://solito.dev
It's a powerful solution for small/medium teams working on a new project.

_Problems I faced:_
- opinionated solution —which is good! but in my case, I needed to add Native Base and I ended up having issues with webpack to make things work.

_Should I recommend it?_
Yes! The doc is up-to-date, @nandorojo has put a lot of effort into this solution.
Took me 3 hours to setup a project, add a UI library `react-native-paper` and ship it to production on Vercel.

_Does it benefit Ignite?_
Not sure.

2. https://github.com/flexbox/react-native-universal-monorepo  - `Android` - `iOS` - `Windows` - `MacOS` - `Android TV`  - `tvOS` - `Web` - `Web - Browser Extension` - `Web - Electron` - `Web - Next.js`
used https://github.com/mmazzarolo/react-native-universal-monorepo

_Problems I faced:_
- Same as before, trying to add a native base and make it work on all platforms

_Should I recommend it?_
Not really, it's a nice learning resource tho! but I encountered a lot of headaches trying to bump all the dependencies

_Does it benefit Ignite?_
I don't think so.
It's a nice reference to have if you want to work with yarn workspaces.

3. https://github.com/flexbox/react-native-nx-monorepo `react-native` + `react-native-web`
used https://nx.dev/packages/react-native

_Problems I faced:_
- The learning curve, reading this book helped me to ramp up on "thinking in monorepo" https://go.nrwl.io/react-book

_Should I recommend it?_
Yes! The [DX is mindblowing](https://twitter.com/flexbox_/status/1551982652181209088).
There is documentation and that's what "Big Enterprises Corporations" are looking for: how to maintain software over time.

_Does it benefit Ignite?_
Could be. 
Nx is a maintained product with a [dedicated engineering team](https://nrwl.io/about-us). YOu should catch up with @xiongemi
Nx allows to share code —right now I have 3 differents

**Comment by thipokch** [comment]
Was there any reason why Ignite migrated away from monorepo?

**Comment by astriskit** [comment]
what happened to this issue? And I'm wondering why there is no `@nx/ignite` at par with `@nx/expo` and `@nx/react-native`?
@flexbox - kudos to awesomely compiled response above; I'm curious, did you also try ignite-cli generated app in a monorepo setup such as nx? Thanks.

**Comment by flexbox** [comment]
> And I'm wondering why there is no @nx/ignite
because infinite red is not a GAFAM FAAM whatever giant tech company with thousands of engineer to maintain it 😅 
[And they are busy with other awesome things](https://chainreactconf.com/).
In a ideal world we could have such, but the reality is every company tend to have their own monorepo solution based on their needs. So there is no point trying to please everyone were the "problem" is more politic / organisational and not really a tech issue.

>did you also try ignite-cli generated app in a monorepo setup such as nx
No because i work as a freelance. I do not feel confident to scaffold an "exotic solution" and leave the team alone without any documentation.
I think you can, but i would not recommend because you will spend time on plumbing (especially if you want to share stuff following the nx way) instead of shipping actual features to your users/products.

@astriskit what kind of app are you building that needs a monorepo?

**Comment by astriskit** [comment]
@flexbox thanks for answering. And agreeable reasoning. :)

App is for a fintech product in crypto space. The plumbing that I was engaged up till like yesternight here has come to a bitterness of overdoing it; I wanted to fill it (sort of re-starting) with kitchen-sink for web and mobile along with a shared space for a web app. But in light of the real work(the features, screens, current-scope, team, etc.), this became tiny and insignificant very fast for the project - nothing writing some e2e and unit tests can't cover, I believe; Web-app can also be built through the expo/metro rather than shelling it in a separate app (using a different stack). That being said, it was a learning streak - `nx`, `yarn workspaces`, `@nx/expo`, `@nx/react`, monorepo setups.

**Comment by joshuayoes** [comment]
Reactotron has a monorepo with an example ignite app embedded in it:

https://github.com/infinitered/reactotron/blob/master/apps/example-app

Reactotron uses nx as a task runner but not much else of nx features. This would be a good example to reference of what it would look like to setup an app in a yarn 3 monorepo setup.

**Comment by joshuayoes** [comment]
Here is the initial PR @morganick created that could be useful for reference 

https://github.com/infinitered/reactotron/pull/1411

**Comment by joshuayoes** [comment]
In general, the most complicated part of a monorepo setup is making sure that all the config files in the root of an ignite app workspace resolve correctly:
- metro.config.js: Metro can resolve, watch, and link any workspace aliases
- babel.config.js: Metro/Babel can resolve any workspace aliases for the JS bundle
- tsconfig.json: Typescript can resolve workspace aliases for type checking 
- react-native.config.js: if you are using React Native CLI instead of Expo for some reason, it needs to know where to resolve workspace aliases


The other tricky part is what package manager you use. npm, yarn, pnpm, and bun all have subtle nuances that affect where workspaces and node_modules are resolved from. These differences are part of why it's tricky to make _one true recipe_.

**Comment by fpena** [comment]
Working on doc/recipe [here](https://github.com/infinitered/ignite-cookbook/pull/173).

**Comment by astriskit** [comment]
That's cool. Thanks.
