### ISSUE TITLE
[Maverick] Debug apk size:168 mb, release apk size: 63 mb.

### ISSUE THREAD

**Issue by maqeelqureshi** [infinitered/ignite#2240]
I have generated a fresh app and its size is 168 mb for debug and 63 mb for a release apk. It was 45-60mb in older versions.

Please suggest any solution to reduce it.

**Comment by frankcalise** [comment]
Hi @maqeelqureshi! Thanks for the interest in Ignite :)

You can check out some tips on reducing bundle size here in a previous issue: https://github.com/infinitered/ignite/issues/1947#issuecomment-1223985929

**Comment by maqeelqureshi** [comment]
> Hi @maqeelqureshi! Thanks for the interest in Ignite :)
> 
> You can check out some tips on reducing bundle size here in a previous issue: [#1947 (comment)](https://github.com/infinitered/ignite/issues/1947#issuecomment-1223985929)

I have already checked it. I need to distribute apk (microsoft appcenter). Aab is not working on appcenter.

**Debug apk size = 168 mb**
lib size = 156 mb 

arm64-v8a = 41.9 mb
armeabi-v7a = 27.3 mb
x86 = 44 mb
x86_64 = 42.8 mb

**Release apk size = 63 mb**
lib size = 54.2 mb

arm64-v8a = 14mb
armeabi-v7a = 10.1 mb
x86 = 14.6 mb
x86_64 = 15.3 mb

**Comment by frankcalise** [comment]
Hi @maqeelqureshi - unfortunately we cannot control that AppCenter does not allow the app bundle (aab). However, I would look to remove any other unused code and/or libraries that are not necessary to your project and go from there. Have you done this as well?

**Comment by maqeelqureshi** [comment]
@frankcalise I have recently created an app using legacy ignite. Its size is 39 MB for release and 56 MB for debug apk. 

I am worried about new apk size, if my app is migrated to ignite 8 as there are many project specific libraries. I am expecting it would reach to 80-90 mb if migrated.

Following is the comparsion of dependencies of both ignite8 PizzaApp and my full featured app.

New libraries in ignite 8,

    "@expo/webpack-config": "",
    "date-fns": "",
    "expo": "",
    "expo-application": "",
    "expo-constants": "",
    "expo-device": "",
    "expo-file-system": "",
    "expo-font": "",
    "expo-modules-core": "",
    "expo-splash-screen": "",
    "expo-status-bar": "",
    "react-native-bootsplash": "",
    "@expo-google-fonts/space-grotesk": "",
	
Common libraries between ignite8 and my app,

    "@react-native-async-storage/async-storage": "",
    "@react-navigation/bottom-tabs": "",
    "@react-navigation/native": "",
    "@react-navigation/native-stack": "",
    "@react-navigation/stack": "",
    "apisauce": "",
    "expo-linear-gradient": "",
    "expo-localization": "",
    "i18n-js": "",
    "mobx": "",
    "mobx-react-lite": "",
    "mobx-state-tree": "",
    "react": "",
    "react-native": "",
    "react-native-gesture-handler": "",
    "react-native-reanimated": "",
    "react-native-safe-area-context": "",
    "react-native-screens": "",
    "reactotron-mst": "",
    "reactotron-react-js": "",
    "reactotron-react-native": ""

Other project specific libraries in my app,

    "react-native-restart": "",
    "react-native-signature-canvas": "",
    "react-native-splash-screen": "",
    "react-native-sqlite-storage": "",
    "react-native-svg": "",
    "react-native-swipe-list-view": "",
    "react-native-tab-view": "",
    "react-native-timeline-flatlist": "",
    "react-native-unimodules": "",
    "react-native-vector-icons": "",
    "react-native-webview": "",
    "reflect-metadata": "",
    "rn-async-storage-flipper": "",
    "rn-flipper-async-storage-advanced": "",
    "styled-components": "",
    "styled-system": "",
    "validate.js": "",
    "yup": ""
    "appcenter": "",
    "appcenter-analytics": "",
    "appcenter-crashes": "",
    "@react-native-community/push-notification-ios": "",
    "@react-native-community/datetimepicker": "",
    "@react-native-community/masked-view": "",
    "@react-native-community/netinfo": "",
    "@react-navigation/drawer": "",
    "formik": "",
    "@unimodules/core": "",
    "native-base": "",
    "react-native-animatable": "",
    "react-native-camera": "",
    "react-native-camera-hooks": "",
    "react-native-code-push": "",
    "react-native-collapsible": "",
    "react-native-curved-bottom-bar": "",
    "react-native-flipper": "",
    "react-native-fs": "",
    "react-native-geolocation-service": "",
    "react-native-image-viewing": "",
    "react-native-keychain": "",
    "react-native-loading-spinner-overlay": "",
    "react-native-mail": "",
    "react-native-maps": "",
    "react-native-multi-selectbox": "",
    "react-native-multi-switch": "",
    "react-native-pager-view": "",
    "react-native-permissions": "",
    "react-native-push-notification": "",

**Comment by frankcalise** [comment]
@maqeelqureshi Ignite's set of libraries are often for what we most commonly use here at Infinite Red for client projects. There is absolutely no obligation to keep things just because it was listed in the latest version if you don't have any use for it, so you are free to trim it down as you see fit! This is a boilerplate which is to be used as a guide, not necessarily something you must follow once you initialize the app.

For example, are you using Expo? If you are then you can remove the android/ios directories and also `react-native-bootsplash`.  (You don't need expo-splash-screen AND react-native-bootsplash)

Don't plan on using `space-grotesk` font? You can remove this too.

`expo-modules-core` is not new to Ignite v8.

If you have your own date library you plan to use or don't need one, feel free to remove `date-fns`.

`expo-application` and `expo-device` are useful for debugging purposes and tracking device information, but if you don't need these then feel free to remove them.

It's really up to you to know your application and what libraries are required and are not. I can only speak to what is used for the demo application, but if your use case is not to run the demo application as-is, then there are definitely packages you can remove to cut down on the size.

Hope that helps!

**Comment by frankcalise** [comment]
Going to close this, feel free to drop by in our [community slack](https://community.infinite.red/) if you want to discuss best practices for bundle reduction with the team and other Ignite developers, I'm sure they have some great ideas as well!
