### ISSUE TITLE
react-native 0.70

### ISSUE THREAD

**Issue by saeedghasemi72** [infinitered/ignite#2272]
Hi guys,
Do you have any plan for upgrade to 0.70 and new architecture? :)

**Comment by frankcalise** [comment]
Hi @saeedghasemi72 thanks for the interest in Ignite!

We plan on keeping RN upgraded along with Expo's recommended version for the boilerplate. However, it is just that, a starting boilerplate! Feel free to go through the upgrades yourself after you Ignite a new project.

As far as the new architecture goes, there is a lot that goes into fully supporting this. For one, since we do include many packages in our project to start, we need to make sure that they all support the new architecture.

In addition to that, we are preparing the native side as best we can to support the new architecture when it is a bit more mature.

Hope this helps!
