### ISSUE TITLE
Demo with real use of Header

### ISSUE THREAD

**Issue by ryskin** [infinitered/ignite#2300]
That's great Header comp is included in the library but there is no example of how to use it "right". For example, I usually include it in the Screen component but there are some problems with the insets. Maybe there is a better way to use it? I want to know how infinitered integrates Header in projects )

Thanks for all you do for the community!

**Comment by ryskin** [comment]
@yulolimum you are the best, I will follow your recommendation, you just made my day

**Comment by jamonholmgren** [comment]
If you want to use @yulolimum's suggestion 2, here's a small convenience hook:

```tsx
import React from "react"
import { useNavigation } from "@react-navigation/native"
import { useLayoutEffect } from "react"
import { Header, HeaderProps } from "../components"

/**
 * A hook to set the header for a screen.
 */
export function useHeader(headerProps: HeaderProps, deps: any[] = []) {
  const navigation = useNavigation()

  useLayoutEffect(() => {
    navigation.setOptions({
      headerShown: true,
      header: () => <Header {...headerProps} />,
    })
  }, deps)
}
```

You use it like this in your screen:

```tsx
  useHeader({
    rightTx: "common.logOut",
    onRightPress: logout,
  })
```

We could, perhaps, include it in Ignite if @yulolimum likes this approach.

**Comment by ryskin** [comment]
@jamonholmgren thanks for the addition, I will use it

I think need to include both variants in the demo, so the user can choice.

**Comment by ryskin** [comment]
Just tried and it's so simple and works great, hooks are my choice. I can make a different file for option if I need to reuse it many times.

**Comment by yulolimum** [comment]
@ryskin 

Documentation added to https://github.com/infinitered/ignite/blob/master/docs/Components-Header.md#usage

`useHeader()` hook added: https://github.com/infinitered/ignite/blob/master/docs/Utils-useHeader.md

[Header updated](https://github.com/infinitered/ignite/blob/master/boilerplate/app/components/Header.tsx#L168) to use insets instead of SafeArea using new hook: https://github.com/infinitered/ignite/blob/master/docs/Utils-useSafeAreaInsetsStyle.md

Thx!
