### ISSUE TITLE
Changing theme colors from withing the app at runtime

### ISSUE THREAD

**Issue by a0v0** [infinitered/ignite#2340]
Similar to how telegram allows you to create custom theme

**Comment by cr4zyc4t** [comment]
haha, you must rewrite theming system using React Context API
And not just theming, you can't change language at runtime either because dev team decided that i18n-js is better than react-i18next :))

**Comment by Kiura** [comment]
@cr4zyc4t This looks so bad... since I am rewriting my app (still using ignite), I added a new theming system to support changing the theme at runtime. if I use my method, I have nice UX, but I have trouble keeping the codebase up to date with ignite. Or if I use the default theming system, I have worse UX, but better codebase manageability.

**Comment by lindboe** [comment]
Addressed by #2636.
