### ISSUE TITLE
About Icons. Not necessarily an enhancement I guess but wondering.

### ISSUE THREAD

**Issue by 2Senn** [infinitered/ignite#2480]
First of, I love this template. Thanks alot.
Second, I noticed you do not use react-native-vector-icons in your boilerplate code. Is there a reason for this? do you not want to deal with the configuration or is it for efficiency reasons? just curious!

**Comment by frankcalise** [comment]
Hey, thanks for the appreciation - it means alot! ❤️ 

We don't include that because typically our projects incorporate custom assets for icons, so we would just end up uninstalling it when we take on a new client (as Ignite represents what we usually use when jumping into a new client project).

You absolutely can add vector icons either natively or through an Expo Dependency. There are also considerations to make when bringing in font icon sheets as they can increase bundle size quite a bit if not careful.

See these threads for more info:
https://twitter.com/Baconbrix/status/1676329985064435712

https://twitter.com/Baconbrix/status/1676330442474274817

**Comment by 2Senn** [comment]
Thanks for the quick and very helpful response ! 
One more thing, would it be possible that you create a recipe for incorporating react-native-maps in the project? as we use it quite heavily and I personally love everything you guys write so was curious to see the implementation and different things that could be done.

Thanks again!

**Comment by frankcalise** [comment]
Yeah we can look into that, if you wouldn't mind making an issue over there. This was just asked the other day actually, see this for more info:

https://github.com/infinitered/ignite/issues/2478#issuecomment-1623709219
