### ISSUE TITLE
Please add redux support

### ISSUE THREAD

**Issue by EndLess728** [infinitered/ignite#2595]

**Comment by abtonc** [comment]
[Here are the reasons](https://shift.infinite.red/why-infinite-red-uses-mobx-state-tree-instead-of-redux-d6c1407dead) why ignite uses MST instead of Redux.

And the team will be removing MST from the boilerplate in the future (they are still recommending it.

You can still remove MST code and add your Redux code.

**Comment by frankcalise** [comment]
@EndLess728 as @abtonc mentioned, redux will not be the default in this boilerplate for those reasons. However, you could request a recipe be done over at https://github.com/infinitered/ignite-cookbook/issues
