### ISSUE TITLE
Creating bare react native project without expo

### ISSUE THREAD

**Issue by saif-o99** [infinitered/ignite#2651]
### Describe the bug

when i run `npx ignite-cli@latest new PizzaApp` and go through the steps ...
when i select bare project or expo, both looks the same for me.
i know the bare project will still contain some expo packages but i litreally don't see a difference.

Am i missing something or there is something wrong?

### Ignite version

9.6.2

### Additional info

System
  platform           win32
  arch               x64
  cpu                12 cores     AMD Ryzen 5 5600X 6-Core Processor
  directory          saifo        C:\Users\saifo

JavaScript (and globally-installed packages)
  node               20.10.0      C:\Program Files\nodejs\node.EXE
  npm                10.2.3       C:\Program Files\nodejs\npm.CMD
    corepack         0.22.0
    npm              10.2.3
  yarn               1.22.19      C:\Program Files (x86)\Yarn\bin\yarn.CMD
  pnpm               -            not installed
  bun                -            not installed
  expo               -            not installed

Ignite
  ignite-cli         9.6.2      
  ignite src         build       

Android
  java               17.0.10      C:\Program Files\Microsoft\jdk-17.0.10.7-hotspot\bin\java.EXE
  android home       -            C:\Users\saifo\AppData\Local\Android\Sdk

Tools
  git                git version 2.43.0.windows.1   C:\Program Files\Git\cmd\git.EXE

**Comment by ManojVarmaNVK** [comment]
True. May i also know what's difference bare and Expo? As in bare project we are again using expo dependencies

**Comment by saif-o99** [comment]
An off topic question, im wondering why the IOS folder is not showing anymore in the projects created with ignite? 🤔

**Comment by frankcalise** [comment]
Ignite always includes Expo in it's version today. Bare is just an option where the native directories are created so you can feel free to manage them yourself.

@saif-o99 you can choose CNG/Bare to have the iOS folder present. Expo will generate this for you the first time. It's not in the repo anymore because we don't maintain it.

You could certainly Ignite a project with an older version if you are looking for the old vanilla experience, pick something from version 8.x. If you are looking for a template without Expo at all, you can clone something like https://github.com/frankcalise/ignite-vanilla-template

Hope this helps!

**Comment by saif-o99** [comment]
@frankcalise thanks for your help. I created a bare project but i only sees the android folder.

**Comment by frankcalise** [comment]
@saif-o99 that's because you're on windows, it can't generate the native files for ios because you don't have MacOS with CocoaPods etc
