### ISSUE TITLE
Update boilerplate/README.md

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2653]
## Description
After you Ignite a new app, there is a generated README.md - it's a bit outdated in terms of directory structure, what next steps are, etc. We should update this to be more helpful

**Comment by turquoisemelon** [comment]
Hello 👋🏻
I would like to help, if this issue is still relevant! On an initial look, I see [Boilerplate.md](https://github.com/infinitered/ignite/blob/master/docs/boilerplate/Boilerplate.md) file under docs folder seeming to have similar but more up-to-date content to [generated README.md](https://github.com/infinitered/ignite/blob/master/boilerplate/README.md) (Boilerplate.md updated a month ago). Would it make sense to port that over to generated README.md?
