### ISSUE TITLE
[Example App]: Does not respect iOS light/dark mode

### ISSUE THREAD

**Issue by DandyLyons** [infinitered/ignite#2775]
### Describe the bug

The example app does not respect the iOS device's light/dark mode appearance setting. 
This happens on iOS 18, on device and in simulator. 

The example app has basically no customizations at all. It is the stock example app, generated by the Ignite CLI. 

From a console.log I was able to determine that `useColorScheme()` is correctly updating in real time. 
When I replace `AppStack` with my own custom view, then my custom view respects the device's light/dark mode appearance. (More specifically the header respects it but nothing else. I'm using `headerLargeTitle:true`).

For more context, see: https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1726086216120089 

### Ignite version

9.10.0

### Additional info

npx ignite-cli doctor
System
  platform           darwin                                                                           
  arch               arm64                                                                            
  cpu                8 cores         Apple M1                                                         
  directory          NotVoiceMemos   /Users/daniellyons/Developer/React Native Projects/NotVoiceMemos 

JavaScript (and globally-installed packages)
  node               22.5.1       /Users/daniellyons/.nvm/versions/node/v22.5.1/bin/node    
  npm                10.8.2       /Users/daniellyons/.nvm/versions/node/v22.5.1/bin/npm     
    corepack         0.29.2                                                                 
    expo-cli         6.3.12                                                                 
    npm              10.8.2                                                                 
  yarn               1.22.22      /opt/homebrew/bin/yarn                                    
  pnpm               -            not installed                                             
  bun                -            not installed                                             
  expo               51.0.32      managed                                                   
  expo global cli    6.3.12       Deprecated: Found 'expo-cli' installed. Please remove it. 

Ignite
  ignite-cli         9.10.0       /Users/daniellyons/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/daniellyons/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.24      /opt/homebrew/opt/openjdk@11/bin/java 
  android home       -            undefined                             

iOS
  xcode              16.0       
  cocoapods          1.15.2       /Users/daniellyons/.gem/ruby/3.3.4/bin/pod 

Tools
  git                git version 2.39.5 (Apple Git-154)   /usr/bin/git 
(base)

**Comment by frankcalise** [comment]
Hey, theming will be supported in version 10, which you can try via `npx ignite-cli@next`

**Comment by DandyLyons** [comment]
Does that mean it’s not supported in the library as a whole, or just not in the example app? 

We should probably update the docs to say that it’s coming in version 10.

**Comment by frankcalise** [comment]
@DandyLyons React Native and Expo support the ability to theme your application and acquiring the user's operating system's theme choice.

The example app is not implemented in a way which supports it, in version 9. The example app is just a starting place to understand some of the architecture behind Ignite. Of course you are free to start there (or start from scratch) and implement it if you choose.

I'm going to close this since there are multiple issues tracking this already:
- #2340  
- #1879 

I feel like the docs do a decent job of describing what Ignite is, its features and how to use it at https://docs.infinite.red. It doesn't mention that theming is supported (theming is more work than just looking at the value of `useColorScheme`). If you think it would be helpful to add explicitly that theming support isn't yet supported, a PR would be welcome! Modify the markdown in `docs/` and we would be happy to review it.

If you're newer to Ignite, keep in mind that it is originally designed to help our team at Infinite Red kick off projects, which is mostly what the boilerplate represents. There are some things we don't target even if they are requested by the community or understood to be more popular. We do make it open source so that it's a useful starting point for others and you are free to make changes that you see fit.
