### ISSUE TITLE
*Feature Request* Extensible nav system

### ISSUE THREAD

**Issue by DavidBates** [infinitered/ignite#280]
While the hamburger approach to nav is fine and dandy I would like to port an existing application over to ignite that uses https://github.com/exponentjs/react-native-tab-navigator instead of a hamburger menu. 

I asked on gitter for a way to do this and was directed here to file an issue for tracking. 
It's my belief that with an extensible nav system that supports either the hamburger or tabBar ignite would cover 90% of native app navigation systems. 

Thanks
David Bates

**Comment by GantMan** [comment]
@DavidBates - Agreed!   We have some apps using tabs already!   One thing we want to do is expand our example set of what the app should do.

Now, there's a clean existing example of `react-native-tabs` in RNRF https://github.com/aksonov/react-native-router-flux/blob/master/docs/DETAILED_EXAMPLE.md

I'd be interested in seeing which one is better.   I assume most people will go with this one, because the example is already completed, but I know exponentjs do excellent work!   So perhaps you can help us construct the tab example inside of ignite?   If that's not your bag, then we'll probably get around to it soon enough :)  We just love seeing outside code.

**Comment by DavidBates** [comment]
Sounds good. I am writing an app based on that example, I'll see what I can do.

**Comment by pekkanikolaus** [comment]
If anyone had any hints how to properly transition from the hamburger menu to tab navigation inside Ignite, I’d be very grateful! I’m still new to all this and scared of doing something the wrong way.

**Comment by zzimbler** [comment]
@DavidBates @GantMan Also working on a tab based application. Are you working on your version in the public? I'd be happy to help and discuss

**Comment by skellock** [comment]
In Ignite 2, we're hoping to launch with `react-navigation`.  This becomes much easier to do with their stacks.
