### ISSUE TITLE
eslint support?

### ISSUE THREAD

**Issue by kxxoling** [infinitered/ignite#284]
Would there be eslint support just like other start-kit, eg. vue-cli, do. So that I could choose which eslint config while starting a new project.

**Comment by GantMan** [comment]
The issue with opening up eslint at the generator is that it would automatically give you a headache of things to worry about, and you'd have to convert a lot of the existing code.

That's why we're linting to standard by default, or we'd be stuck writing all of our generators in multiple linting formats.   Once something has been generated, feel free to convert it to your eslint rules that fit your needs.

I hope this answers your question :)
