### ISSUE TITLE
Drawer animation super slow Android & iOS

### ISSUE THREAD

**Issue by rknell** [infinitered/ignite#296]
Hi All,

New to react to excuse me if i'm doing something wrong, coming from the Ionic / Angular Material / Ionic2 and obviously Cordova world that I'm pretty well versed in. One of my big reasons for making the jump is obviously performance and especially the performance of drawer animations... Which is why I am so surprised its as bad as it is.

To reproduce just fire up a vanilla ignite project and click on the drawer, iOS simulator is bad, Nexus 6P is pretty terrible, this is after I removed all the content on the presentation screen as well. I looked at the perfmonitor and the JS framerate is all that drops to around ~30 FPS, the device one stays at 59.6. I wouldn't have though 30FPS wound't be that bad but it look and feels like its about 5.

Anyway I'm not here to have a winge, I was just wondering if someone has resolved the issue already, its being worked on, or how I could implement this (and is it likely to work):
https://github.com/root-two/react-native-drawer/issues/163

If I can solve it I am happy to do a pull request.

There are a few threads of react-native-drawer's github page around performance but I figured its probably more of a configuration issue with ignite since every post isn't about it.

**Comment by GantMan** [comment]
Heya @rknell !   Welcome!

So, yes the dev experience _feeeeeeeels_ like it's 5 frames per second, but in my experience the problem is usually being in development mode.

By default, we have Redux logger, yellow box, reactotron, and packager remote.  All performance inhibitors.  When you turn all these off and ship to a device with the JS bundled neatly inside, the performance usually mirrors native speeds.

I know that doesn't sound good for fishing out performance smells on local dev, but having all those bells and whistles really helps app creation.   I suggest putting your app on a device once a week to make sure you're actually hitting native speeds.

If you notice any issues on device, please let us know!  If not, we're interested in how we could communicate these development costs in the future.  Perhaps in the readme, or a blog post, or perhaps indicators on the actual screen?

**Comment by harisvsulaiman** [comment]
Development on an android device is super  slow, especially the navigator animations and the drawer animatons.

**Comment by CharlieIGG** [comment]
Can confirm this, once you build the APK it all runs surprisingly smoothly @rknell

**Comment by skellock** [comment]
Great news.  Ya, `console.log` is amazing just how bad it beats up RN android.  Reactotron was partly born out of this pain.
