### ISSUE TITLE
Component examples screen is very laggy

### ISSUE THREAD

**Issue by pradel** [infinitered/ignite#335]
In ignite-base "Component examples screen" is very laggy (opening page with transition and scrolling). All the other pages are find.
Tested on nexus 5X with android 7.0.

**Comment by GantMan** [comment]
This is common on android with debug mode.  A signed APK is usually fast.

**Comment by skellock** [comment]
Are you running debug mode?  Or did you bundle & are running in production?  All `console.logs` removed?

https://github.com/infinitered/ignite/issues/296 might be related too.

This is a common concern for React Native apps.  There's many strategies for dealing with it.  Ignite doesn't prescribe the right approach as every app is different.

If you look into the InteractionManager, there's a way to defer JS-heavy things until after UI interactions are finished.

If you're going to a screen that has lots of controls that are instantiated, perhaps there's a way you can find to pre-warm that screen so it takes the hit at app launch time instead of navigation time?

Nice to hear that it works on Android 7 though!  I haven't tried that yet.  :)

If you still feel this is an Ignite issue and not React Native, please reopen and let's chat.

**Comment by pradel** [comment]
Okay good to know,  thanks for the response !
Are you interested in a PR adding some warning for android users for this page ?

**Comment by skellock** [comment]
Sure!
