### ISSUE TITLE
Can Ignite be used for iPad or Universal apps?

### ISSUE THREAD

**Issue by pekkanikolaus** [infinitered/ignite#395]
The projects Ignite generates are iPhone only on the iOS end.
I just switched it to Universal in XCode, and the results are... very nice! The UI adapts nicely to the bigger screen. The hamburger menu is obviously clunky on an iPad pro, but I was going to replace that anyway by a tabbed nav.

Apart from the obvious (providing alternative layouts where needed, etc. etc.), is there anything I need to be aware of when developing an iPad or Universal app with Ignite?

**Comment by GantMan** [comment]
Nope!   By default it should be pretty good!   We've made 2 ipad apps with Ignite, and they've been awesome!  

The reason it's not set to Universal by default, is because we follow whatever React Native has given us... but in all honesty, I don't know why they don't default to Universal.   We could, of course, switch it to universal by default.   I'm glad you're enjoying Ignite!  Let us know if you find any issues with iPad and we'll happily make a ticket for it.
