### ISSUE TITLE
Not sure why the ignite.json file changed back to .ignite.... 

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#432]
- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [X] ignite the cli
 
--- 
Hello

I know we originally had an `.ignite` file in the base directory for config options. I changed this in #383 to `ignite.json` and added this [comment](https://github.com/infinitered/ignite/pull/383#issuecomment-249093672). 

Then, in ea5790d887e35c425bf8c7e6230d3683cd3c15f1, it got changed back to `.ignite`....

Was there a reason for this? I ask because its broken my test generator for components, and try as I might I can't get the .ignite file to read in, it just comes back null all the time....

![image](https://cloud.githubusercontent.com/assets/7445602/19420725/4ab1f4ee-944e-11e6-9713-f8bd00f12a46.png)

**Comment by GantMan** [comment]
Ah yes.  So a couple of reasons why this happened.

I'm actually not sure why it works for me and not your machine, but I want to find out rather than hide the problem. I actually tested this on 3 machines.  It worked just fine.  So rather than lose the benefits, let's dig into this. 

> Benefits of `.ingite` over `ignite.json`
* `.ignite` is a hidden file on most systems.  Keeping it clear from those who don't need to worry about it.
* `.ignite` as a javascript file allows benefits over JSON
  * JS can include functions
  * JS can have comments
  * JS can optionally import further
  * JS can have detailed object structures

 If you can import javascript files, why wouldn't you be able to import `.ingite`?  Is it a naming issue?  If it were called `heyheyhey.js` does the import then work?  Let's solve this riddle.
![image](https://cloud.githubusercontent.com/assets/997157/19422292/cb3b3b56-93d7-11e6-9bad-c09984e7e0c7.png)

**Comment by juddey** [comment]
Great Response! :) I can see the reasons behind the *.js vs. *.json so no need to wax on about that. We just need to get it working on this side of the world (ok, lets just start with my machine first. Small steps.)

I'm on OSX El Capitan (if thats relevant).

Heres my file:
```
{
  "igniteVersion": "1.7.1",
  "reactNativeVersion": "0.33.0",
  "options": {
    "testing": "ava"
   },
  "plugins": {}
}
```

Did a little testing - changing both the filename in `utilities.js` and the actual file name:
* `ignite.json` => ✅ 
* `.ignite` => ❌ 
*  `ignite.js` => ❌
*  `.ignite.json` ✅ 
*  `.ignite.js` => ❌
* `.ignite.xml` => ❌ 
* `ignite.xml` => ❌  

Thoughts?

**Comment by GantMan** [comment]
you can't require a `ignite.js` file?

One thing that stands out is you're not exporting your object in ignite.  You should have module.exports at the top:
https://github.com/infinitered/ignite/blob/master/ignite-base/.ignite.template

**Comment by juddey** [comment]
Yep, that got it. 💥  Thanks!
