### ISSUE TITLE
[RFC] Simplify Types

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#44]
@GantMan was saying he didn't like our `Types.js` structure how we're repeating keys & values.

Facebook solves this with `keyMirror`. 

What are the thoughts on this?  Good? Bad? Unclear? Just inventing another reason to use Ramda?

```js
// createTypes.js
export default R.pipe(
  R.trim,
  R.split('\n'),
  R.map(R.pipe(R.trim, R.toUpper)),
  R.map((x) => [x, x]),
  R.fromPairs
)

// Our new Types.js
import createTypes from './CreateTypes'

const types = `
push
pop
login_success,
login_request,
login_failure
`

export default createTypes(types)
```

Ramda playground to riff:  http://goo.gl/KIVfQ5

**Comment by GantMan** [comment]
I think this is time for a lib folder, and an exposed function to generate types.

**Comment by GantMan** [comment]
after speaking with @skellock on this.  `createTypes`, `createReducer`, `createAction` and soon to be `createSagas` will all come from a common lib.   The big ? is the name, since 75% of the code for this already done.

### Ideas:
* `reduxSauce`
* `rouxDux`  - I like this because roux makes sauces... also, I'm southern.
* `reduxGenesis` - playing on all the create prefixes
* `gantIsSexy` - probably already taken on npm

**Comment by GantMan** [comment]
With Undefined action type checks in place, we have another odd case we need to catch.

I want a command for safe merging.   If your initial state shape has X keys, it should always have X keys.  When you do a merge, it should severly warn, and even crash in dev, if you merge in a new value.

Today I worked with @fvonhoven and he had a merge that had a typo, and it was causing all hell to break loose.  This is something we could have easily avoided by overriding the default state merge with a simple wrapper.

**Comment by GantMan** [comment]
completed by moving to separate lib
