### ISSUE TITLE
Include Selectors into Ignite-base

### ISSUE THREAD

**Issue by gavin-gmlab** [infinitered/ignite#451]
### Feature/Enhancement

mapStateToProps seems to be called fairly often, sometimes even when the component container is not in the foreground. For more complex applications with a large state tree, this might mean unnecessary processing when something unrelated in the state tree changes. To consider using memoized selectors https://github.com/reactjs/reselect to prevent performance problems

**Comment by skellock** [comment]
Heyo.  I'd actually push back on this a bit.   Reselect does look interesting, but I think that being specific about what emerges from your `mapStateToProps` might be a lot easier.

Smart components will fire upon every single state change.  If `mapStateToProps` emerges something that's not equal to what it was last time, it'll check with `shouldComponentRender` before calling render.

Because of that, I feel like React already has the tools to solve that particular problem.

My objection is only to "out-of-the-box" Ignite support, not really to Reselect itself or to people using it.

Just my opinion of course.  For some apps, Reselect might be a godsend.  I'm just not sold on "most" apps.

Caveat:  I've never used that library, this was only a knee-jerk reaction after looking at it.  😍

**Comment by kevinvangelder** [comment]
This sounds to me like something that should be optional via a generator (or manually if it's easy to set up).

**Comment by colbydehart** [comment]
I second this, having selectors and a generator for selectors would be very useful. Since reselect selectors are memoized, any kind of calculation that needs to be done in mapStateToProps can be avoided if the input selectors used in the calculation have the same output as last time. It just adds an extra layer of efficiency to rendering. 

Also, aside from `mapStateToProps`, selectors can also be used in a saga with the `select` effect, meaning if you need to pull in state during a saga, it gets the same performance gains you are using in your `mapStateToProps`

Thirdly, selectors are composable, meaning you can use one selector as the input for another, which is great for nested or derived slices of data from state. This helps cut down on duplicated code when two smart components need to operate on similar pieces of state.
 
This helps take a lot of the logic of transforming pieces of your state from your UI components as well. Instead it places this logic into testable selector functions. I find `mapStateToProps` is the peskiest place for business logic to creep into my presentation logic and this has helped me a lot.

**Comment by skellock** [comment]
Awesome thoughts @colbydehart !

I agree with you about the presence of selectors.  I'm a big fan of them.

Reselect will only speed up the contents of the state selection.  Which is already quick. 

They still have to flow back into a component, and you'll still have a check in `shouldComponentUpdate `.  This is where I'd spend my time performance updating.  What you do in here will have massive impact.

I'd have to really see the performance impact of slow selectors to buy into Reselect.

My two Canadian cents.

**Comment by skellock** [comment]
The good news is that selectors can be written by "sporking" the redux template in Ignite 2.0.  Also you can write your own generators now.
