### ISSUE TITLE
Reactotron doesn't log redux actions dispatched from react-sagas

### ISSUE THREAD

**Issue by Obsessive** [infinitered/ignite#469]
- [x ] Issue does not already exist
Actions dispatched from containers are logged but the same actions when dispatched from react saga using 'put' are not logged.
We have setup manual reactotron logs to ensure actions are in-fact dispatched and corresponding sagas are run .

Is this expected behaviour or something is amiss? 

```
Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.5.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.3
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.33.1
```

**Comment by skellock** [comment]
Ya.  This makes me sad.

It has to do with the internals of redux store enhancers.

Basically, the order of the enhancers matter.  If you put reactotron first, it can't dispatch to redux saga.  If you put reactotron last, it can't listen to actions dispatch by redux saga (which is what you're experiencing).

Some more info here:  https://github.com/reactotron/reactotron/issues/131

There are work arounds... each have their pros and cons.  

And now literally since I'm answering this, I think I know another way I can try it.  

If I were to break Reactotron's redux's enhancer into two parts (one for dispatching and one for logging) I think I can make this work... 

I'll have a look at this in the next few days.  Thanks for logging this issue.

I'll close this here, but feel free to open another issue over on [Reactotron](https://github.com/reactotron/reactotron/issues/new) citing this one.  Ignite is an innocent victim of my own bugs.  <3

**Comment by skellock** [comment]
Tracking here: https://github.com/reactotron/reactotron/issues/228

**Comment by skellock** [comment]
Fix incoming tomorrow https://github.com/reactotron/reactotron/pull/230.  It also got much easier to configure Reactotron with redux.  That was a nice by-product of this fix.
