### ISSUE TITLE
Question: Transition Overlay Color

### ISSUE THREAD

**Issue by mxmtsk** [infinitered/ignite#516]
Hey, I'm using ignite to dig in to react native a bit more and I've played around a lot to see what happens and at some point I noticed this weird faded white overlay when transitioning between scenes and I have no idea where I could enabled / changed it. I'm completely lost so I am asking if someone can point me in the right direction?

![unbenannt-1](https://cloud.githubusercontent.com/assets/4848184/20729354/eed736d8-b681-11e6-914b-bdcd3f68c7a0.jpg)

**Comment by skellock** [comment]
[This color](https://github.com/infinitered/ignite/blob/master/ignite-base/App/Themes/Colors.js#L20) is griefing you [because of this](https://github.com/infinitered/ignite/blob/adad3406a1ede0deda9a51f03de1a959a2767e75/ignite-base/App/Navigation/Styles/NavigationDrawerStyle.js#L10).

I got hung up on this before as well.
