### ISSUE TITLE
[2.0] Generate

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#547]
I don't know what the intended behavior is, so that's the problem.

![image](https://cloud.githubusercontent.com/assets/997157/21287348/e0665394-c42e-11e6-9978-159d0cda3ec3.png)

I thought calling generate lists generators.... is this no generators?  What exactly is a user looking at?

**Comment by skellock** [comment]
This is up to us to figure out as we build this CLI.

What do we want to display when there are no generators?  No errors?  When there are errors loading anything?

We need something to display more than nothing tho.

Since generators are 3rd party (including `ignite-basic-generators`), they are sourced from the `node_modules` from the current directory.  The directory you're in doesn't have them.

This is why i created `packages/ignite-empty-playground`.  That will have everything installed in it.

Try `cd ../ignite-empty-playground` and try again.   It should list the generators detected.
