### ISSUE TITLE
[2.0] Ignite New

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#567]
`ignite new` should be started.

Take these examples as functional minimums.  The actual experience can have spinners/friendly graphics etc.

version 1:  Answers "no" to everything.  Perfect for regen playground. Simply uses https://github.com/infinitered/ignite/issues/568
```js
ignite new SomeProject --min
Congrats! SomeProject has been generated
```

version 2:  Answers "yes" to everything. Great for testing.
```js
ignite new SomeProject --max
Congrats! SomeProject has been generated
```

version 3: Composer experience
```js
ignite new SomeProject
Welcome to Ignite - The Unfair Headstart Generator

The following questions will help us choose your additional goodies.

Would you like the Ignite Development Screens? (y/n)
y
...
...
Congrats! SomeProject has been generated
```

**Comment by ericvera** [comment]
I've been playing with the v2 for the last couple of hours and have a v0.1 of the new command. It still needs some work, but thought I'd share it before investing too much on it. If this works let me know and I can create a pull request once I add a bit more validation. Otherwise let me know of any suggestions on a better approach.

Approach [new.js](https://github.com/ericvera/ignite/blob/next-new-verb/packages/ignite/src/plugins/default/commands/new.js):
1. Create a new directory (`<new app name>`) under the current working directory
2. Call `ignite add ignite-basic-structure <new app name>` using the new directory as the cwd

Considered Approach:
 - Call cli.js directly and require the ignite-basic-structure generator directly. Since each of those deal directly with the parameters passed to the command line, that would require refactoring the code to be able to pass the valued from the new command.

**Comment by ericvera** [comment]
This is what it looks like at the moment.

```
Erics-MacBook:ignite-range eric$ devignite new Papaya
🏠  Papaya has a new home at /Users/eric/Code/ignite-range/Papaya
🔥  installing ignite-basic-structure
    ✔︎  index.ios.js
    ✔︎  index.android.js
    ✔︎  README.md
    ✔︎  ignite/ignite.toml
    ✔︎  .editorconfig
🍽  time to get cooking!
Papaya is now all yours!

To run in iOS:
  cd Papaya
  react-native run-ios

To run in Android:
  cd Papaya
  react-native run-android
```

**Comment by kevinvangelder** [comment]
@ericvera Looks like a great start to me, but @GantMan and @skellock are the real masterminds, so I'd look for their feedback before continuing. This already covers most of the functionality of the proposed `--min` option.

**Comment by ericvera** [comment]
There are a few things that I am still not sure what your intended design is. Did you intend to run `react-native init <project name>` (I have not added this yet) and then run the ignite-basic-structure generator?

**Comment by skellock** [comment]
Thanks for the input @ericvera. I'd like to see `ignite-basic-generators` rolled into `ignite` personally.

I think you'll see a lot of refinements next week though as the team is getting together in person.

And yes, our starting point is `react-native init EricApp`.

**Comment by skellock** [comment]
@ericvera I just re-read your comment.  I didn't realize what you were saying is: you're building it.

@GantMan has built `new` and we're just tweaking it now.  We're going in stages.  We've got unholy (what we're calling ignite 1's kitchen sink approach) up & running now, and we're going to bust those into plugins next.

I appreciate the help though.  Perhaps what we can do is start tagging a few tasks with Help Wanted on Ignite 2 going forward.

**Comment by GantMan** [comment]
awesome thoughts @ericvera -  I think Ignite 2.0 in one week will look very different.   Keep your ear to the ground here on github to see the transformation as we go through it 👍

**Comment by GantMan** [comment]
@skellock , should this have been closed?

**Comment by skellock** [comment]
I think so.  `ignite new` has been built.  

Feel free to open this up if you think i'm overlooking something.

**Comment by GantMan** [comment]
Just thinking the --min --max hasn't been put in yet.  The original ticket had those.

**Comment by skellock** [comment]
Okie dokie.

**Comment by kevinvangelder** [comment]
@ericvera We made a lot of progress on 2.0 this week. Feel free to check out the latest code on `next` as well as the new issues we've filed to get an idea of where we could use help.

**Comment by skellock** [comment]
Done.
