### ISSUE TITLE
[2.0] Printout after questions is odd

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#634]
take a look at this:
![image](https://cloud.githubusercontent.com/assets/997157/22432746/876951f4-e6db-11e6-92ce-b385d50ba2a2.png)

Looks like it asks questions several times, when you go back and look at it.  What's up with that?

enquirer lib bug?

**Comment by skellock** [comment]
I've seen the duplicates on 1 line, but this is the first time I've seen it THAT bad. Hah!

Something is not right.

**Comment by kevinvangelder** [comment]
This got much worse when I switched the Dev Screens question to be the list type. I meant to mention it in the PR but forgot.

**Comment by jamonholmgren** [comment]
I've replicated this issue with a barebones `prompt-list` and `enquirer` repo and filed an issue.

https://github.com/enquirer/prompt-list/issues/2

**Comment by jamonholmgren** [comment]
I just tested using Inquirer instead of Enquirer and it works fine. We would lose these prompt types (unless there are plugins for these, which there possibly are -- haven't checked):

radio
question
autocomplete

For now, I'm going to introduce a dependency on Inquirer into Ignite until prompt-list is fixed and then we can switch back to the Gluegun one. Or if Gluegun switches to Inquirer too.
