### ISSUE TITLE
Startup Saga called twice when starting up an app

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#715]
The startup saga is being called twice when starting up an app. 

![image](https://cloud.githubusercontent.com/assets/7445602/23185943/1b5aea6a-f8ea-11e6-9666-1052271834c7.png)

![image](https://cloud.githubusercontent.com/assets/7445602/23185802/9332c3e2-f8e9-11e6-9503-16b109b6a5a3.png)

**Comment by skellock** [comment]
If you're using `redux-persist`, then let it handle startup timing.   Since the state could take a while to render, only `redux-persist` knows when it is ready to dispatch `startup()`.

Firing it twice in our sample app doesn't do any damage, but a real app might have unintended consequences.

Good catch guys.

**Comment by skellock** [comment]
We should comment out the dispatching to `startup()` inside the `RootComponent.js` and replace it with:  'UNCOMMENT THIS IF YOU ARE NOT USING REDUX PERSIST' or something ominous.

**Comment by skellock** [comment]
I hadn't realized that [this was already in place](https://github.com//infinitered/ignite/blame/master/ignite-base/App/Containers/RootContainer.js#L16).

@juddey can you confirm you didn't have that line of code?  I feel like that's exactly what we need and it's already there.

Thx

**Comment by juddey** [comment]
Yep, I didn't have that line of code. Was probably b/c I came from a much earlier version of  ignite.

Closing now.
