### ISSUE TITLE
nothing happening in install in some spots

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#717]
I only caught a second of it.  But there are long pauses of nothing

![nothing](https://cloud.githubusercontent.com/assets/997157/23189684/bdb69d5e-f859-11e6-8bb8-fc8beb414e84.gif)

**Comment by skellock** [comment]
gotcha.  You have to turn off the spinner before printing, so in the weaving I missed something.  Thx for reporting.

**Comment by jamonholmgren** [comment]
So we have a problem here that I worked on for about an hour and don't see a particularly elegant solution to. Every time we spawn a new process like `ignite add i18n` there's a pause before the `ignite-i18n` package starts displaying its own output.

The solution I attempted was to try displaying our own output in the template while these packages were installing. That way we could kick off a spinner before spawning the process and kill it when the process is completely done.

The problem is that each of these plugins is supposed to handle their own spinners. So, in order to do this, we'd need to make sure to run `ignite add <package> --app-template` and have each plugin check to make sure they're not running as part of an app template and suppress the spinner output if so.

There are a number of issues with this. One is that the process is now opaque to us in the app template, so all we know is the process is running, not that it's installing or linking or whatever. I don't think it's a good thing to lose this detail. Another issue is that if the package author forgets to suppress output, it starts competing with the app template's spinner output, which results in flickering.

I'm now implementing a hack that will display a brief "initializing <packagename>" message and then stop the spinner on a timeout. It'll at least let the user know that something's happening. Not a great long-term solution, probably, but also probably good enough to ship.

**Comment by jamonholmgren** [comment]
This isn't too bad. I think we can live with this. If someone has a faster machine than me or for whatever reason `ignite add` runs much faster, we'll need to tweak the temporary spinner timeout from its current 8 seconds.

![ignite-new2](https://cloud.githubusercontent.com/assets/1479215/23346044/8e0f36d8-fc4b-11e6-8364-56796cbe77f0.gif)
