### ISSUE TITLE
Pare down the ignite commands to what is feasible.

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#845]
Currently I can be in any folder and type `ignite` and I'll see every option.
![image](https://cloud.githubusercontent.com/assets/997157/23583129/1c77557c-0101-11e7-8752-3ac8ad93cd21.png)

Technically some of these are not proper for a user, but they must be typed find that out.   
![image](https://cloud.githubusercontent.com/assets/997157/23583143/5f560028-0101-11e7-9c90-bf053c64e47b.png)

^ see?  The very first command listed and **RED TEXT**.   An experienced Ignite user knows... but a non-experienced ignite user immediately gets nada!

So my suggestion is, when you're in an empty folder you get:
```
  doctor         Checks your dev environment for dependencies.
  new (n)        Generate a new React Native project with Ignite.
  plugin (p)     Manages ignite plugins
  version (v)    Prints current version of installed ignite
```
🌅  Ahhhh, so clean, so friendly.

and when you're in an Ignite project, you get:
```
  add (a)        Adds an Ignite plugin.
  doctor         Checks your dev environment for dependencies.
  generate (g)   Generates some files.
  plugin (p)     Manages ignite plugins
  remove (r)     Removes an Ignite plugin.
  spork          Copy templates as blueprints for this project
  version (v)    Prints current version of installed ignite
```
w00t!  What a great set of options that all make sense!

**Comment by skellock** [comment]
This is a great idea.

**Comment by mlaco** [comment]
*pare

**Comment by mlaco** [comment]
I'm trying this

**Comment by mlaco** [comment]
In order to allow some commands to be show only within an ignite folder, and
others outside, a change is required in Gluegun. The hidden status of a command
is determined by the presence of certain strings in the content of source
files. Practically speaking, they are determined at compile-time. I thought of
a way we could do this.

Introduce a dynamic option that is invoked with a particular keyword that would
go in the place "true" is usually found. For example, near the top of Ignite's
add command is this line:

`@cliAlias a`

Change the token finder in Gluegun to look for that. When the option is
detected, Gluegun will check the directory for a file. In our case, this would
be a directory sharing the name with the plugin. There might be more options
people want, but this is all we would need.

How this would look in a command file such as Ignite's add command:

`@cliHidden whenExists /ignite/ignite.json`

Gluegun would then look for ./ignite/ignite.json in the cwd

Thoughts?

**Comment by mlaco** [comment]
I guess another option would be to change some of [this](https://github.com/infinitered/ignite/blob/master/src/cli/cli.js#L11-L14), and evaluate whether cwd is an ignite directory there. It would be a lot simpler and wouldn't require changing Gluegun.

**Comment by mlaco** [comment]
Steve gave me the idea to hijack and modify `print-commands` [from Gluegun](https://github.com/infinitered/gluegun/blob/1.x/packages/gluegun/src/cli/print-commands.js) so that we can control the logic determining whether each command shows up in the help message.

I understand the change that’s needed in print-commands, but I don’t know where I should perform that modification. It can’t be in `/ignite/src/cli/cli.js` because that isn’t run just once. Is there an npm after-install script or something that would work?

**Comment by jamonholmgren** [comment]
@mlaco I'd like to still do this, but basically we'd just need to do something custom here:

https://github.com/infinitered/ignite/blob/6e8145c6a0a589bf56da4f3fda807bcdd8e66175/src/commands/help.ts#L13
