### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by evelan** [infinitered/ignite#881]
What's going on?

![screen shot 2017-03-07 at 10 16 26](https://cloud.githubusercontent.com/assets/1548104/23649681/95c9a540-031f-11e7-8cd4-8f228e2b37e8.jpg)

---
Steps to reproduce

```
npm install -g ignite-cli
ignite new igniteTest

🔥 igniting app igniteTest
✔ using the Infinite Red boilerplate
✔ added React Native 0.42.0
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
✔ added ignite-ir-boilerplate-2016
✔ added ignite-dev-screens
✔ added ignite-vector-icons
✔ added ignite-i18n
✔ added ignite-animatable
✔ configured git

cd igniteTest
react-native run-ios
```
---
`ignite doctor` results:

```
System
  platform           darwin                                                                                                   
  arch               x64                                                                                                      
  cpu                8 cores                                             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz  
  directory          /Users/evelan/Programowanie/project/igniteTest                                                       

JavaScript
  node               7.6.0        /usr/local/bin/node  
  npm                4.1.2        /usr/local/bin/npm   
  yarn               0.20.3       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.42.0      

Ignite
  ignite             2.0.0-beta.3   /usr/local/bin/ignite  

Android
  java               1.8.0_112    /usr/bin/java               
  android home       -            /usr/local/opt/android-sdk  

iOS
  xcode              8.2.1       

```

**Comment by skellock** [comment]
Are you running your packager?  Are there errors when you run that?

**Comment by stormpat** [comment]
I just tried ignite 2.0 out, and i have the same issue.

**Comment by sandelld** [comment]
ditto. exact same issue when trying Ignite 2.0 - have created other react native projects without a problem but get this when using Ignite

**Comment by sandelld** [comment]
I can get project to work by running 'react-native run-ios' a 2nd time while the error is up... I originally thought my issue was caused by using multiple iTerm windows but it persists even when sticking to a single one.

**Comment by describeme** [comment]
bump

**Comment by VirenMohindra** [comment]
bump

**Comment by michaellujan** [comment]
Adding more context, here is output from packager: 

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: .../Documents/github/test/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with .../Documents/github/test/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: .../Documents/github/test/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with .../Documents/github/test/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (.../Documents/github/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (.../Documents/github/test/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
~
Process terminated. Press <enter> to close the window

**Comment by skellock** [comment]
The latest version of react-native-router-flux has included a version of `react-native` in their dependencies.  I recommend locking to `3.38.0` of `react-native-router-flux` until [they get it sorted](https://github.com/aksonov/react-native-router-flux/issues/1803).

We've [pinned it](https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/29) but need to release a new version on npm which @jamonholmgren is hooking us up with tonight.

**Comment by skellock** [comment]
Another option is to install `ignite new MyApp -b ir-next` which uses our more bleeding edge version of the boilerplate.  This uses `react-navigation` instead of `react-native-router-flux` which we're transitioning out of.

Apparently a lot sooner than we'd expected after the day we had.  ;P

**Comment by jamonholmgren** [comment]
New version of `ignite-ir-boilerplate-2016` is [now available](https://github.com/infinitered/ignite-ir-boilerplate-2016/releases/tag/v0.2.2) on NPM. You don't have to do anything to upgrade; simply run `ignite new TestApp`. @evelan @michaellujan @VirenMohindra @describeme @stormpat @sandelld

**Comment by micahosborne** [comment]
I just ran this like literally before you posted and i'm still having the same issue

**Comment by VirenMohindra** [comment]
Works for me @jamonholmgren, but I also ran `npm install -g ignite-cli` for safety.

**Comment by aaayushsingh** [comment]
more than 1 year after this issue was closed and I'm still facing it. Any help?

**Comment by jamonholmgren** [comment]
@aaayushsingh Do you have a way to reproduce the issue? That would really help!

**Comment by aaayushsingh** [comment]
I created a new app reading steps from readme and ran it. 

The problem was with bundler not starting. I ran the app again once bundler had started and then it worked fine. 

I did face another issue with i18n-js although it was installed and linked. I've given up on igniter!

**Comment by kevinvangelder** [comment]
If I remember correctly, React Native 0.42 and previous versions had issues where running `react-native run-ios` didn't consistently launch the React Native Bundler, so most users manually started the bundler to resolve this type of issue. Have you tried this with newer versions of RN?

**Comment by aaayushsingh** [comment]
@kevinvangelder I can't say what version of react-native the project was using because I've deleted it. I was using Ignite Andross and was using whatever was bundled in it. react-native-cli version is 2.0.1 which I suppose is irrelevant.

This issue was fixed easily by running react-native run-ios again but there was another issue with react-native-i18n initialization too. Something about undefined is not an object in i18n-js(althouth the library was installed and linked properly). 

I don't think such issues should exist with cli's in the first place because if I'm unable to get a starter app running in less that 30 minutes then it's not worth it.

**Comment by kevinvangelder** [comment]
Sorry you had a bad experience. Since you originally opened this issue back in early 2017 it's likely you were using one of the versions of RN that had this issue.

Not to argue with you, but we have hundreds of users that are generating Ignite projects on a regular basis and as far as I know most of them aren't running into the issue with i18n, there's probably some edge case that was causing you to see different results from most users.

I agree, we want to fix these issues wherever possible, but I think that Ignite offers roughly two weeks of value (particularly to inexperienced React Native developers) in the form of researching and deciding which packages to use as well as preconfiguring them, so even spending a few hours getting things working would be worthwhile. But, obviously, it's been a lot longer than that in your case, and I'm sorry we couldn't get things working for you. Hopefully someday you'll get an opportunity to give us another shot, but either way, I wish you the best of luck with your development endeavors.
