### ISSUE TITLE
Command for creating project plugins

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#916]
The `ignite plugin new thing` will create a npm-based plugin.  Project plugins are a lot more simple.

Let's create a plugin version that will create these.

Anyone have a preference?  I'm leaning towards 2.

### 1. A new command
```sh
ignite plugin-project new something
```

### 2. Prompt for it
```sh
ignite plugin new something

# Choose a plugin type:
# > npm-based
#   project-based
```

### 3. Add a switch
```sh
ignite plugin new something --project
```

Project plugins are the same as normal plugins, except:

* they don't install node_modules
* they don't have a plugin.js
* they can't be boilerplates

But they awesome for:

* generators
* custom scripts

/cc @jamonholmgren @GantMan and anyone else who wants to share their thoughts.

**Comment by jamonholmgren** [comment]
I like number 3, the switch, which kind of surprises me, since I'm usually kind of anti-switch on CLIs. But of the options you put forth, that makes the most sense.

Other options:

```sh
$ ignite plugin new something --local
$ ignite plugin new something --no-npm
$ ignite plugin new something --bare
```

I'd be okay with number 3, another option when generating. If we do that, I'd probably say something like:

```sh
$ ignite plugin new something

# Choose a plugin type:
# > npm package
#   local only (generators and/or scripts)
```

Just thinking out loud here.

**Comment by skellock** [comment]
We could do both 2 and 3. Just need to figure out the wording. Maybe it could be a yes/no question?

Will this plugin be installed on npm?

**Comment by fvonhoven** [comment]
I'd say number 2...because it eliminates the handling for inherent use cases for 1 & 3...namely:
What is the default behavior when not passed a switch (3) or just run (1)?
A user shouldn't have to know the menu of options/switches to be able to use the cli (plenty of gotchas or voodoo behind the scenes that they'd never even know about)...
Let's make it so easy even a caveman could do it...

**Comment by skellock** [comment]
Alrighty.  Sold.  Prompt is default.  And a flag can auto-answer the prompt, just like what we do for the boilerplates with `--min` and `--max`.

**Comment by GantMan** [comment]
I'm late to the party, but I was gonna say combine 2 and 3, lol.

**Comment by fvonhoven** [comment]
![alt tag](https://media.giphy.com/media/VUOMN3AJbxSeY/giphy.gif)

**Comment by jamonholmgren** [comment]
This hasn't gotten a lot of support, so I'm going to close it.
