### ISSUE TITLE
react-native-cli version not detected correctly

### ISSUE THREAD

**Issue by SteveOscar** [infinitered/ignite#940]
---
What's going on?  
I've already used Ignite 1, now trying to create a new Ignite 2 app and getting an error about react-native-cli not being up to date, but it is. I've tried uninstalling the Ignite 1 packages and reinstalling react-native-cli.  `ignite doctor` shows the correct version of react-native-cli.

![image](https://cloud.githubusercontent.com/assets/12125888/24334220/1f32f10c-1224-11e7-9a7e-c4aa2f373a60.png)
---
Steps to reproduce
`npm install -g ignite-cli`  
`ignite new MyApp`
---
`ignite doctor` results:
![image](https://cloud.githubusercontent.com/assets/12125888/24334214/09e068d4-1224-11e7-8bfe-d845d22b0441.png)

**Comment by evert-smit** [comment]
Hi Steve, I had the same issue while trying out Ignite. I haven't looked into the exact workings of the Ignite source, but it seems to be looking for the react-native-cli package locally instead of globally. If you install react-native-cli locally:

`npm install --save react-native-cli`

Ignite will pick it up and work - perhaps not the nicest solution, but if it helps you continue your project until this is fixed officially, maybe you could try it. I'm using 'ignite attach' myself so I won't be looking into it any further, I'm afraid. Hope this helps!

**Comment by SteveOscar** [comment]
@evert-smit yeah I had it installed globally, thanks for the tip!

**Comment by Amnesthesia** [comment]
Been messing around with this issue for days -- @evert-smit's solution definitely seems to solve it. Not super nice to have a `node_modules` drifting around on its own but it works

**Comment by jamonholmgren** [comment]
Sorry to hear you all are having this issue! This often happens if you have `react-native` (instead of `react-native-cli`) installed globally. Generally, doing this should fix it.

```
npm uninstall -g react-native
npm install -g react-native-cli
```

I deployed an early detection script in beta 8 in #934 but apparently it's not catching this well enough. Anyone who runs into this issue who can provide more context to help tweak the early detection code would be very appreciated.

**Comment by jamonholmgren** [comment]
#949 related? @skellock

**Comment by skellock** [comment]
Yes.
